### ISSUE TITLE
Can't create new resource using AdminUI

### ISSUE THREAD

**Issue by drphrozen** [valdisiljuconoks/localization-provider-epi#1]
I'm unable to create new resources using the AdminUI anymore.. I can activate the new resource elements by removing the "hidden" class manually from the dom element.

**Comment by valdisiljuconoks** [comment]
This was deprecated and finally removed.

More details here:

https://blog.tech-fellow.net/2018/01/31/some-smaller-updates-for-<https://blog.tech-fellow.net/2018/01/31/some-smaller-updates-for-dblocalizationprovider/>dblocalizationprovider<https://blog.tech-fellow.net/2018/01/31/some-smaller-updates-for-dblocalizationprovider/>/<https://blog.tech-fellow.net/2018/01/31/some-smaller-updates-for-dblocalizationprovider/>

Get Outlook for Android

________________________________

**Comment by drphrozen** [comment]
Ahh.. Thanks, we have a loose coupled approach to resources. The plugin solved an big issue for us (having static files with resources) but all we really needed was a different way to store and update resources.
Binding resources to backend code is not our prefered solution.

That being said, it's a nice plugin you have created, and it helped us greatly for a time, thanks 👍

**Comment by valdisiljuconoks** [comment]
it might however survive in new admin UI version ;) feature supported code is not throw out yet..

**Comment by markeverard** [comment]
+100000000 :)
