### ISSUE TITLE
fromcode always zero after restart

### ISSUE THREAD

**Issue by mhwlng** [valdisiljuconoks/localization-provider-epi#10]
Hello,

in the example alloy project from issue #9  I added some resources

synchronisation of newly found resources at startup works ok. (fromcode = 1)

but now all resources suddenly have fromcode field = 0 after a restart ?
and don't get updated anymore when text in source code changes ?

If I do this:
`update [LocalizationResources] set FromCode = 1`
then restart
all rows have FromCode = 0 again

```
SELECT [Id]
      ,[ResourceKey]
      ,[ModificationDate]
      ,[Author]
      ,[FromCode]
      ,[IsModified]
      ,[IsHidden]
  FROM [EPiServerDB_1848eeb6].[dbo].[LocalizationResources]
```

```
Id	ResourceKey	ModificationDate	Author	FromCode	IsModified	IsHidden
37	Alloy.Resources.FaqResources.WhatAreYouLookingFor	2019-03-08 10:33:59.290	type-scanner	0	0	0
38	Alloy.Resources.FaqResources.NoMatchingResults	2019-03-08 10:33:59.293	type-scanner	0	0	0
39	Alloy.Resources.FaqResources.MoreInformation	2019-03-08 10:33:59.293	type-scanner	0	0	0
40	Alloy.Resources.FaqResources.ViewAllQuestions	2019-03-08 10:33:59.293	type-scanner	0	0	0
41	Alloy.Resources.FaqResources.BackToTop	2019-03-08 10:33:59.297	type-scanner	0	0	0

**Comment by valdisiljuconoks** [comment]
jump to 5.4.1 version for [AspNet package](https://www.nuget.org/packages/LocalizationProvider.AspNet/5.4.1) and sync should be back. sorry for issue.
