### ISSUE TITLE
Javascript Resource Handler gives object reference not set

### ISSUE THREAD

**Issue by Sebbe** [valdisiljuconoks/localization-provider-epi#11]
Good day,

I'm trying to use the DbLocalizationProvider.EPiServer.JsResourceHandler, and have added 
`@Html.GetTranslations(typeof(Translations))`
to my layoutfile, unfortanly it doesn't work for my project and I just get a "Object reference not set to an instance of an object"
![bilde](https://user-images.githubusercontent.com/814625/54182153-fce78c00-44a0-11e9-8127-59497405b1fe.png)

I guess it have something to do with that that file have lots (then I mean lots) of nesting, and something goes wrong futher down, but I'm not sure how to debug this. Any tips?

Here is my translation file
https://gist.github.com/Sebbe/fb8171cbc10a4ece7090c460011ff052

**Comment by valdisiljuconoks** [comment]
speculation - try to add `[LocalizedResource]` attribute to nested classes as well. To save time - I would either try on single class (rest commented out) or just massive pattern match/replace to add attribute to zillions of classes.

IMHO nested classes are ignored by default, but looks like json handler is not able to handle that ;)

**Comment by valdisiljuconoks** [comment]
I haven't tried this scenario myself tho..

**Comment by Sebbe** [comment]
Doesn't look to help, but it helped in for that I now can write f.eks http://new.norrona.no/jsl10n/Norrona.Commerce.Framework.Translations.ProfileResources and I will get that resources... even nesting inside of that one

**Comment by valdisiljuconoks** [comment]
All resources have translations? Can you reproduce it in Alloy?

**Comment by Sebbe** [comment]
Yes all have translations, but i found the issue now.

https://gist.github.com/Sebbe/fb8171cbc10a4ece7090c460011ff052#file-translations-cs-L1223

if you look at that line, then you can see that I call that property `reset` but the parent property is also called reset, and thats the reason it fails for some reason. So I have now renamed that property and everything works as expected. Thanks for the quick answers, just wish I didn't use 8 hours to debug this in diffrent ways ^^

**Comment by valdisiljuconoks** [comment]
this is weird. but I think trouble might be in the `public ResetResources Reset { get; }` line..

**Comment by Sebbe** [comment]
Maybe, but if I just add a t to the property and then it works. (if starting from a new alloy)
I found another issue in my solution, and that is we have some translations that is only in the DB
The resource key is like this:
`Norrona.Commerce.Framework.Translations.Search.Sort.Options.Concepts `
and then I also get the null reference exception
So that one I can fix with cheating in my code and not look for sort, but for something else :)

Another issue is that it doesn't use fallback language? Should I make a new issue for that?

**Comment by valdisiljuconoks** [comment]
which version you have of the lib?

**Comment by Sebbe** [comment]
Latest (5.4.0)
But start to look like it is something in my DB too... Right now I have a fix where i run a delete on your two tables while the site is down. Then site starts and add everything back from code, then I take a import from production and include all but Sort and a couple more. Looks like that solves it, expect that if I try a new import from same file, then I get a new error :') 

![bilde](https://user-images.githubusercontent.com/814625/54273425-26c6ae80-4586-11e9-9034-4f9f6ba86a8f.png)

**Comment by valdisiljuconoks** [comment]
there are couple higher minor versions as well for aspnet lib. can you share translations json file? it's terrific error handling btw ;)

**Comment by Sebbe** [comment]
ofc, I'm glad for all help I can get :')
True, I upgraded it just now to see if it had a affect ^^ same errors :/

https://gist.github.com/Sebbe/a3a207c129e1d844544526b03f6d77ed

**Comment by valdisiljuconoks** [comment]
all language brancheswntioned in exported file are enabled in epi, right? and also invariant culture?

did fallback solved automagically with minor jump or still fallback is ignored?

**Comment by Sebbe** [comment]
Actualy, I didn't see that earlier after upgrading to latest on aspnet lib, but after upgrading that to 5.4.1 I get this error
![bilde](https://user-images.githubusercontent.com/814625/54277827-2c75c180-4591-11e9-8d78-9ad1c50ace76.png)

So downgraded that package and it works again. I may have done something wrong, so don't look to much into that, I will try again later

Anyway, everything works as expected when I use `@Html.Translate(() => Translations....)` then fallback work as expected, but when I look in the json file from the js library, then I see that those that is missing translations, get null as value.

Branches mentioned in export is in use yes, but how do I check for invariant culture?

**Comment by valdisiljuconoks** [comment]
do you have ideas why you do have null resources in db?

**Comment by valdisiljuconoks** [comment]
is it so that you have null translations for the resource keys that *are* coming from code?

**Comment by valdisiljuconoks** [comment]
so basically fallback is sort of working. it's much more challenging to get it working properly according to Episerver settings. As Episerver fallback logic is based on single resource invoke, in JsHandler context we need to translate whole object will all keys, etc. Theoretically it could be so that one property exists in given language, another does not.

so a bit more info:

![image](https://user-images.githubusercontent.com/1767179/54287660-c435d880-45ae-11e9-921b-5471c87a881c.png)

here I'm asking for Norwegian language, but does not exist for that property - so lib falls back to invariant.

if you have time, try also fork repo and see if you can spot different in included sample alloy site from yours..

**Comment by Sebbe** [comment]
Yeah, I don't have the invariant Language, so I will try to add that and get all english translations inside of it :)

Thanks for the help, I i will fork and try to recreate my issues

**Comment by valdisiljuconoks** [comment]
also, can you share your init module for setting localization up in epi?

**Comment by Sebbe** [comment]
Erm, I don't think I set the localization up anywere expect in the config file. Need to do a search for that, but can't remember I did that when I started using this

**Comment by valdisiljuconoks** [comment]
ok, no worries. then you use all defaults.

**Comment by valdisiljuconoks** [comment]
hi, dod you get any further with this?

**Comment by Sebbe** [comment]
Sorry, haven't had time to do it yet. Will keep you posted once I do :)

**Comment by valdisiljuconoks** [comment]
this is very likely to be fixed in 5.5.1. give it a shot once it out on feeds

**Comment by Sebbe** [comment]
Checking now, but I think it was a little evil to rename the assembly.. took me a while to understand why things didn't work with just a update

**Comment by valdisiljuconoks** [comment]
update should have all correct configurations added to web.config file. with this update I had to extract handler to AspNet library (to support pure Asp.Net MVC apps as well). tested couple of scenarios - thought I'm covering various cases. Please give me feedback what didn't work out, so I can adjust. It wasn't intended to be evil ;)

**Comment by Sebbe** [comment]
hehe i know :) Not sure why it didn't work when I updated, will try again. It's allways a issue because I have the episerverframework in another config file :/

The solution builds now and I added the handler at top, but for some reason I get 404 on both the deep merge and the translations. I will try the whole update again later tonight... just need to let the sun go down first :D and again, thanks for all the help and I know you are not evil :)

**Comment by Sebbe** [comment]
Trying again now, can confirm that it only removes the handler and doesn't add again.

**Comment by Sebbe** [comment]
Okey, last comment for now :)
Looks like things is nearly working now! Just can't have the word "sort" at the end of the translation key
(Norrona.Commerce.Framework.Translations.Search.Sort, get a null reference expection) but that one I can fix!

Thanks a lot! You are the best and saved me lots of work :D

**Comment by valdisiljuconoks** [comment]
glad to hear you will have now more free time ;)
