### ISSUE TITLE
DbLocalizationProvider.MigrationTool.5.4.0 throws FileLoadException at startup

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#12]
I installed the DbLocalizationProvider.MigrationTool.5.4.0 from Episerver feed, at startup it crashes:
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembl
y 'NDesk.Options, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null' or one
of its dependencies. A strongly-named assembly is required. (Exception from HRES
ULT: 0x80131044)
   at DbLocalizationProvider.MigrationTool.Program.Main(String[] args)

It seems to be that since version 5.0.0 the command line tool is signed, but the dependency NDesk.Options is not. I reverted to version 4.3.2, which is working fine.

**Comment by valdisiljuconoks** [comment]
I thought it's dead and wanted to remove that tool :)

**Comment by nzsb** [comment]
There were 30 downloads :-)
We have more than 1000 resources in 14 languages in our project which we are trying to import, we have no other chance to migrate to DbLocalizationProvider.
We also need the legacy support on long-term, I hope that's not the list to remove :-)

**Comment by valdisiljuconoks** [comment]
ok, no prob. let me think about good alternative here for parsing command line params..

**Comment by valdisiljuconoks** [comment]
v5.4.1 should be back / working :)

**Comment by valdisiljuconoks** [comment]
reopen please if it blows up. netstandard2.0 is required now for the tool to run.

**Comment by nzsb** [comment]
thank you, I will test it as soon as v5.4.1 is published in Episerver nuget feed.
