### ISSUE TITLE
DbLocalizationProvider.AdminUI.EPiServer 5.4.0 XLIFF Export crash

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#13]
When clicking on Export button the an exception is thrown.
The problem seems to be that DbLocalizationProvider.AdminUI.EPiServer.Xliff.dll is strongly named, but Xliff.OM is not signed.

Exception:
 Could not load file or assembly 'Xliff.OM, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.FileLoadException: Could not load file or assembly 'Xliff.OM, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[FileLoadException: Could not load file or assembly 'Xliff.OM, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)]
   DbLocalizationProvider.Xliff.Exporter.Export(ICollection`1 resources, CultureInfo fromLanguage, CultureInfo toLanguage) +0
   DbLocalizationProvider.Xliff.Exporter.Export(ICollection`1 resources, NameValueCollection parameters) +166
   DbLocalizationProvider.AdminUI.LocalizationResourcesController.ExportResources(String format) +104
   lambda_method(Closure , ControllerBase , Object[] ) +104
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +157
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.<>c__DisplayClass24_0.<InvokeActionMethodWithFilters>b__0() +55
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation) +253
   System.Web.Mvc.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2() +22
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation) +253
   System.Web.Mvc.<>c__DisplayClass24_1.<InvokeActionMethodWithFilters>b__2() +22
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +189
   System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName) +521
   System.Web.Mvc.Controller.ExecuteCore() +95
   System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext) +180
   System.Web.Mvc.ControllerBase.System.Web.Mvc.IController.Execute(RequestContext requestContext) +10
   EPiServer.Shell.Web.Mvc.ModuleMvcHandler.ProcessController(IController controller) +40
   EPiServer.Shell.Web.Mvc.ModuleMvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +24
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state) +48
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) +16
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +103
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +159

**Comment by valdisiljuconoks** [comment]
hi,

thx for reporting. seems like you only using export in xliff ;) will need to think what should I do here, as offical xliff package seems to be dead (https://www.nuget.org/packages/Xliff.OM/).. and there are only few alternatives..

**Comment by valdisiljuconoks** [comment]
alrighty, fix is applied and packages are pushed out to the wild. look for 5.4.1 packages for xliff.* stuff.
thanks for reporting!

**Comment by nzsb** [comment]
Thank you, it is working fine!
