### ISSUE TITLE
Prevent model synchronization of Optimizley's dynamic classes

### ISSUE THREAD

**Issue by tholee** [valdisiljuconoks/localization-provider-epi#138]
My apologies for creating an issue. I would have submitted the matter under [discussions](https://docs.github.com/en/discussions) if it were activated.

I'm trying out LocalizedModelAttribute for content types in Optimizley. I noticed that the resource synchronizer includes dynamic proxy types created runtime by Optimizley. 
<img src="https://user-images.githubusercontent.com/1217446/144410388-690cfec8-ee23-4926-97bc-7ddc3fd94602.png" width=40% /><img src="https://user-images.githubusercontent.com/1217446/144410280-3213e31c-7283-4391-abf0-91dbf3405d46.png" width=30% />

It can easily be avoided with ConfigurationContext.AssemblyScanningFilter, but I guess it would be beneficial to exclude dynamic assemblies by default in [ConfigurationContext](https://github.com/valdisiljuconoks/LocalizationProvider/blob/a0322307bdb7515f4a248b17cf18d1c21565c444/src/DbLocalizationProvider/ConfigurationContext.cs#L140).

`ctx.AssemblyScanningFilter = a => !a.IsDynamic && new ConfigurationContext().AssemblyScanningFilter.Invoke(a);`

**Comment by valdisiljuconoks** [comment]
Hey,

No problem. Forgot to open up discussions! But this sounds like a bug. Pulling in for v7 release.. 👌
