### ISSUE TITLE
modules/_protected/DbLocalizationProvider.AdminUI.EPiServer.7.0.0-pre-0006.zip missing in release from DevOps

### ISSUE THREAD

**Issue by murela** [valdisiljuconoks/localization-provider-epi#140]
We have an issue where the DbLocalizationProvider.AdminUI.EPiServer.7.0.0-pre-0006.zip file is not included in the package in DevOps along with other packages.
I suspect that the issue is related to that the .nuspec file in the package (check with download from https://nuget.optimizely.com/package/?id=DbLocalizationProvider.AdminUI.EPiServer&v=7.0.0-pre-0006) differs from 
Nuspec files in package differs from file in https://github.com/valdisiljuconoks/localization-provider-epi/blob/main/src/DbLocalizationProvider.AdminUI.EPiServer/DbLocalizationProvider.AdminUI.EPiServer.nuspec

The one in the package is missing the files-section and has different options for buildAction.

**Comment by valdisiljuconoks** [comment]
Hey, sorry for delay.

Zip files are usually copied in project folder via custom .targets file during 1st build and then it's part of the project.

Can you describe maybe in more details how exactly do you do CI?

Does file exist in source control?

**Comment by murela** [comment]
Hi,

The _modules/protected folder is excluded from source control, and restored in DevOps with "dotnet restore". This is a CMS 12/ Commerce 14 prosject on .net core.
All the other packages in this folder are included in the release, but not this one.

When I compare the one in your package it has different build action than the others that are included. Looking at the file in you Git-repo I can se that is has a lot more than the one in comes with the package from nuget.

**Comment by murela** [comment]
Perfect! Thanks! Can confirm that it's working now.
