### ISSUE TITLE
Resource sync not working

### ISSUE THREAD

**Issue by mkashifanwar** [valdisiljuconoks/localization-provider-epi#154]
Hi, I've upgraded to latest version of DbLocalizationProvider.EPiserver (7.1.0) from 7.0.0-pre-0006 and noticed the sync resources stops working - it does not sync the new resources as well as all existing resources in database were also set to fromcode = false after the upgrade

All other setup is exactly the same apart from some rename changes such as

 .AddDbLocalizationProvider(o =>
                {
                    o.DefaultResourceCulture = CultureInfo.InvariantCulture;
                    o.EnableInvariantCultureFallback = true;
                    o.UseSqlServer(connectionString);
                })
                .AddOptimizely();

 services.AddDbLocalizationProviderAdminUI(_ =>
                {
                    _.RootUrl = "/root";
                    _.AccessPolicyOptions = builder => builder.RequireRole(Roles.CmsAdmins);
                    _.ShowInvariantCulture = true;
                    _.ShowHiddenResources = false;
                    _.DefaultView = ResourceListView.Table;
                })
                .AddOptimizelyAdminUI();

app.UseDbLocalizationProvider();
 app.UseDbLocalizationProviderAdminUI();

Does it requires to do anything special to enable sync?

**Comment by valdisiljuconoks** [comment]
Hi,

It's definitely not by design ;)
Possible to run SQL profiler for your project to see what's going on?

Also you could try to enable diagnostics and check log files.

**Comment by mkashifanwar** [comment]
Hi, it turns out to be it isnt the issue with sync but the way we define resources have changed, in our case we define nested classes to create resources and it seems like we now need to add   [LocalizedResource] at target class level and it works.

However, it comes up with a second issue,

We are defining the [[LocalizedResource(KeyPrefix="Custom")] at top level to not have the fully qualified assembly names in resources, but now it seems to register each resource twice i.e one with Custom.Parent.Child.Label1 and also with FullyQualifiedNameSpace.Parent.Child.Label1.

I have not yet figured out how to force it register once only - but any hint pls?

**Comment by valdisiljuconoks** [comment]
Can you please share parent class and child class code?

**Comment by mkashifanwar** [comment]
hey,

```
 [LocalizedResource(KeyPrefix = "Custom")]
    public  class ParentLabel
    {
        public static MyChildLabels Child { get; }
    }

[LocalizedResource]
    public class MyChildLabels
    {
        public string Label1 => "Label 1";

        public string Label2 => "Label 2";
    }

```

**Comment by mkashifanwar** [comment]
Hi Valdis - did you get a chance to look into this i.e. enable nested model labels?

**Comment by valdisiljuconoks** [comment]
Hi,

Yeah I checked your sample and tested it out also locally. There are few notes from my side:
1) I didn't get neither `Parent.Child.Label1` nor `Custom.Parent.Child.Label1` resources.
2) `FullyQualifiedNameSpace.Parent.Child.Label1` most probably is left-over from before (note that plugin does not delete old resources in db)
3) Complex properties (not scalar data types) should not be treated as resource (unless you mark class with `[LocalizedModel]` or explicitly add `[Include]` attribute for the property).

Tested with following class:

```csharp
using DbLocalizationProvider.Abstractions;

namespace AlloySampleSite.Resources
{
    [LocalizedResource(KeyPrefix = "Custom")]
    public class ParentLabel
    {
        public static MyChildLabels Child { get; }

        [LocalizedResource]
        public class MyChildLabels
        {
            public string Label1 => "Label 1";

            public string Label2 => "Label 2";
        }
    }
}
```

Result:
![image](https://user-images.githubusercontent.com/1767179/157519968-5fcb8de2-cc81-4cf0-a82c-8ca2d65c2049.png)

**Comment by mkashifanwar** [comment]
Hi Valdis,

Thanks for providing feedback - I've tried all the steps again on latest version which v7.2.0.0.

By using the [LocalizedResource] attribute on child classes (complex classes) and by using  [LocalizedResource(KeyPrefix = "Custom")] on parent class - it still register each resource twice for me, and I am making sure to completely delete the database across each run and let Episerver creates new database.

fyi - we've been using the complex resource approach with custom key prefix at parent level since version v6.xxx and its been working like a charm across all upgrades till v7-pre-0006.

So something must have been changed unless you say you are no longer supporting this way of registering resources then I may consider the ManualResource builder option as we've a quite a few classes and using fully qualified resource name won't work well for us in terms of their usage and updating later in UI that's why we've decided to go with shorter custom key prefix.

**Comment by mkashifanwar** [comment]
Another update - the only way I can gets the complex resources registered once is like this as from your above example

namespace AlloySampleSite.Resources
{
    [LocalizedResource(KeyPrefix = "Custom")]
    public class ParentLabel
    {
        public static MyChildLabels Child { get; }
        public class MyChildLabels
        {
            public string Label1 => "Label 1";
            public string Label2 => "Label 2";
        }
    }
}

i.e without using [LocalizedResource] again and keep it as nested class.

**Comment by mkashifanwar** [comment]
Seems like this fix causes the change of behavior https://github.com/valdisiljuconoks/LocalizationProvider/commit/6b84338a08b470ba158d30520f5abc4225584886#diff-5dfd5b004b37eef067f319553ecd093067128e094659c26852d0765cc8409661?

**Comment by valdisiljuconoks** [comment]
Yeah, I was a bit off with my logic description (it's been while since I went in that order of the codebase).
From the scanner logic: if it sees complex child class it checks for `[LocalizedResource]` on declared type (parent class) to verify that scanning should be done for the nested class.

Here is unit test for the logic

```csharp
[LocalizedResource(KeyPrefix = "Prefix")]
public static class ResourcesWithKeyAndComplexProperties
{
    public static ComplexNestedClass NestedProperty { get; set; }

    public class ComplexNestedClass
    {
        public string SomeProperty { get; set; }
    }
}

[Fact]
public void ComplexProperty_OnClassWithKey_PropertyGetsCorrectKey()
{
    var result = _sut.ScanResources(typeof(ResourcesWithKeyAndComplexProperties)).ToList();

    Assert.NotEmpty(result);
    Assert.Single(result);
    Assert.Equal("Prefix.NestedProperty.SomeProperty", result.First().Key);
}
```

If I add `[LocalizedResource]` to child class also - got double registrations:

```csharp
[LocalizedResource(KeyPrefix = "Prefix")]
public static class ResourcesWithKeyAndComplexPropertiesChildClassAttributed
{
    public static ComplexNestedClass NestedProperty { get; set; }

    [LocalizedModel]
    public class ComplexNestedClass
    {
        public string SomeProperty { get; set; }
    }
}

[Fact]
public void NestedClassContainsAlsoLocalizedResourceAttribute_DoubleDiscovery()
{
    var result =
        _sut.ScanResources(typeof(ResourcesWithKeyAndComplexPropertiesChildClassAttributed))
            .Union(_sut.ScanResources(typeof(ResourcesWithKeyAndComplexPropertiesChildClassAttributed.ComplexNestedClass)))
            .ToList();

    Assert.NotEmpty(result);
    Assert.Equal(2, result.Count);
}
```

In last example we get 2 resources because both classes are decorated with attribute and for the scanner it looks like just 2 separate sources for the resources.

This might cover cases when you actually want to use nested classes to organize your resources.
For example:

```csharp
[LocalizedResource(KeyPrefix = "Prefix")]
public static class ResourcesWithKeyAndComplexPropertiesChildClassAttributed
{
    public static string NestedProperty = "test";

    [LocalizedModel]
    public class ComplexNestedClass
    {
        public string SomeProperty { get; set; } = "test (nested)";
    }
}
```

This allows you to use parent class and nested class separately to ask for resources.

Not sure if this is answer you were looking for but at least that is the way how library is treating source scanning unfortunately.

**Comment by mkashifanwar** [comment]
Thanks Valdis,

Yes having nested class as you described above works, but having separate classes with complex class as property inside the parent class it does not scan,

Do you know why this line was added 

if (!typeScanner.ShouldScan(target))
            {
                return Enumerable.Empty<DiscoveredResource>();
            }

at line 64 here https://github.com/valdisiljuconoks/LocalizationProvider/blob/b67ef89683c9f637e26cb3546102fab42aa6a5ca/src/DbLocalizationProvider/Sync/TypeDiscoveryHelper.cs

I think this is what is stopping to scan separate classes without [LocalizedResource] attribue

**Comment by mkashifanwar** [comment]
Hi Valdis,

FYI - Decided treat each class as separate localizedresource to avoid any complexity in terms of scan process - so please consider this issue is closed from my side.

I would also like to say thanks for quick responses, and help and support on this topic.

**Comment by valdisiljuconoks** [comment]
Ok, roger. Treating it as separate resource containers think would be best approach here.

**Comment by sebastian-pierre** [comment]
I'm also having this exact issue, not sure why my setup below is regarded as a complex structure?

```
using DbLocalizationProvider.Abstractions;

namespace Project.ExternalWeb.Domain.Translations
{
    [LocalizedResource]
    public class CommerceTranslations
    {
        public static FieldHeaderTranslations FieldHeaders { get; set; }
    }

    public class FieldHeaderTranslations
    {
        [TranslationForCulture("TestValue 7", "en")]
        [TranslationForCulture("TestValue 7 en-GB", "en-GB")]
        [TranslationForCulture("TestValue 7 es-MX", "es-MX")]
        public string TestValue => "TestValue 7";
    }
}
```

This is also blocked by the typescanner shouldscan.
```
if (!typeScanner.ShouldScan(target))
{
return Enumerable.Empty();
}
```

**Comment by valdisiljuconoks** [comment]
Yeah, probably should add more clarifications on how scanner is working what is treated as complex type.

But might need to review scanner again to see for a quick fix..
