### ISSUE TITLE
Error after upgrade from 6.0.2 to 6.5.2. Duplicate entries bug

### ISSUE THREAD

**Issue by wezz** [valdisiljuconoks/localization-provider-epi#156]
**Error**
We run a website in DXP. 
After upgrading the language provider we got this error in preproduction. 
> The CREATE UNIQUE INDEX statement terminated because a duplicate key was found for the object name 'dbo.LocalizationResourceTranslations' and the index name 'ix_UniqueTranslationForLanguage'. The duplicate key value is (sv, 502).

After downloading the production database I was able to verify that the same issue would have occurred there. 
I found multiple entries in our translations 
<img width="307" alt="image" src="https://user-images.githubusercontent.com/1185533/163337562-66aba6fe-0431-40ce-8f42-2c0ab45328f1.png">

**Debugging**
Running this SQL Query I was able to get an overview of the duplicates in the DB
`WITH cte AS (
  SELECT*, 
     row_number() OVER(PARTITION BY [Language], [ResourceId] ORDER BY [ResourceId] desc) AS [rn]
  FROM [YOURDBNAMEHERE][dbo].[LocalizationResourceTranslations]
)
Select * from cte WHERE [rn] > 1`

**How to reproduce**
I imagine that this process would reproduce the issue:

1. Start with a DB that has been running 6.0.2 of the language provider
2. Add a duplicate entries into the LocalizationResourceTranslations table, where Language and ResourceId have the same values. 
3. Upgrade the language provider to 6.5.2
4. Error will show when the website starts

**Additional thoughts**
My suspicion is that the duplicates occurred due to the DXP deployments are using slots. 
When a temporary slot is spun up and the new code added to it, duplicates might get added to the database since two versions of the code is running against the same database.

The duplicates have one thing in common and that is that they where populated with the attribute
`[TranslationForCulture("Value", "lang")]`

And it is possible that the namespace of these translations has changed multiple times

**Solution suggestions**
Adding a check in the SchemaUpdater for duplicates before the SQL command to create the index is run. 
Either remove duplicates or do not create the index. 
But I don't know how critical the index is at this point.

**Comment by wezz** [comment]
I was able the remove the duplicates with this SQL command
`WITH cte AS (
  SELECT*, 
     row_number() OVER(PARTITION BY [Language], [ResourceId] ORDER BY [ResourceId] desc) AS [rn]
  FROM [DBNAME].[dbo].[LocalizationResourceTranslations]
)
DELETE from cte WHERE [rn] > 1`

Change DBNAME to match the real database

**Comment by wezz** [comment]
I wrote a blogpost on how we worked around this issue
https://www.epinova.se/en/folg-med/blog/2022/executing-custom-sql-command-against-the-optimizely-db/

**Comment by valdisiljuconoks** [comment]
Thanks for detailed description of the issue.

Conclusion is: due to an error in older versions (before the index) there was a possibility to get duplicate rows in the database for the same language for the same resource. Unfortunately - library can't make informative decision about which of the resource should be deleted before proceeding with index creation. Therefore - recommendation is to use approach described in blog post to execute script to remove duplicate resource from the database.

Sorry for inconvenience!
