### ISSUE TITLE
Issue with Vue.js not being defined.

### ISSUE THREAD

**Issue by Alex-Barry-1423** [valdisiljuconoks/localization-provider-epi#161]
Hi there, I've found that after upgrading our Optimizely solution to .NET 6 and the DbLocalizationProvider.EPiServer and DbLocalizationProvider.AdminUI.EPiServer to version 7.3.0 that we are experiencing Vue.js errors that are preventing the localization tab from rendering.

We are registering the service in startup.cs as such...
```
`services.AddDbLocalizationProvider(ctx =>
            {
                ctx.DefaultResourceCulture = new CultureInfo("en");
                ctx.DiscoverAndRegisterResources = true;
                ctx.EnableInvariantCultureFallback = true;
                ctx.EnableLegacyMode = () => true;
                ctx.UseSqlServer(connectionStringCms);
            })
            .AddOptimizely();
```

            services.AddDbLocalizationProviderAdminUI(_ =>
            {
                _.RootUrl = "/localization-admin";
                _.AccessPolicyOptions = builder => builder.RequireRole(Roles.CmsEditors, Roles.CmsAdmins);
                _.ShowInvariantCulture = true;
                _.ShowHiddenResources = false;
                _.DefaultView = ResourceListView.Table;
                _.HideDeleteButton = true;
            })
            .AddOptimizelyAdminUI();`
and then mapping further below like so...
```
`app.UseDbLocalizationProvider();
            app.UseDbLocalizationProviderAdminUI();
            app.UseDbLocalizationClientsideProvider();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapContent();
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
                endpoints.MapDbLocalizationAdminUI();
                endpoints.MapDbLocalizationClientsideProvider();
            });`
```
It seems that any calls to /_content/LocalizationProvider.AdminUI.AspNetCore/js are being refused. Any ideas on what could be causing this?
![image](https://user-images.githubusercontent.com/108350128/176204393-b520cdac-7d86-4533-b030-e63527e73b11.png)

**Comment by valdisiljuconoks** [comment]
Hi, is this happening locally or when a site is being published?

**Comment by valdisiljuconoks** [comment]
Can you get log entries from webserver for these requests? I'm just speculating here - there might be some config missing. Possible to paste full startup code (without sensitive data if any of course)?

**Comment by valdisiljuconoks** [comment]
Ha, interesting, that might be a culprit here. Thx for notifying.

I'll make appropriate tests to see if that's the case.

**Comment by marcosCardona-valtech** [comment]
I am having the same problem but when publishing the site, because locally it works fine. I am getting the same 404's as shown here and in ticket #190 . For some reason all those files are not publishing.

**Comment by marcosCardona-valtech** [comment]
I found the problem, it was our azure deploy pipeline that cleaned the wwwroot/ folder.
