### ISSUE TITLE
Episerver AdminUI XLIFF Export does not export all resources

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#17]
If in AdminUI I export in XLIFF 2.0 Format, it exports only AdminUI resources, it does not export other resources (in my case legacy resources import with MigrationTool). It seems to be regardless of which language or which display view is selected in AdminUI.

With package LocalizationProvider.Xliff.5.4.1
JSON export works fine.

**Comment by nzsb** [comment]
I see, the id is an NMTOKEN. Yes, something like that could work. You could use XmlConvert.EncodeNmToken() before export and decode them at import.
Thank you

**Comment by valdisiljuconoks** [comment]
will be part of v5.5 release
