### ISSUE TITLE
Import button is disabled

### ISSUE THREAD

**Issue by plctremblay-thinkmax** [valdisiljuconoks/localization-provider-epi#176]
The import button is present but disabled. Is there any settings for this or is this a known bug? I have seen a bug related to import button missing but nothing about disabled.

**Comment by valdisiljuconoks** [comment]
Hi,

Import functionality is just upcoming feature (soon to be released). PR for tracking - https://github.com/valdisiljuconoks/localization-provider-core/pull/112

**Comment by valdisiljuconoks** [comment]
Will be part of v7.5
