### ISSUE TITLE
EnableInvariantCultureFallback ignored?

### ISSUE THREAD

**Issue by pamiddleton** [valdisiljuconoks/localization-provider-epi#18]
Hi Valdis, 

I was wondering if you could provide some insight into what I'm trying to achieve with the localization provider. 
I have a requirement where I need to query the provider for localized labels in the fallback languages configured for the current page in EPiServer. 
So for instance, if the fallbacks are defined as en-US => en-GB => en-CA
I want to first see if there is a label for en-US and if not test if one exists for en-GB. 
However when I call GetString(expression, en-US) I always get a label back even though there isn't one configured - it looks like it is falling back to the invariant culture of EN, in which there is a label. 

I have tried setting EnableInvariantCultureFallback to false on initialize but it still appears to fallback. 

`ConfigurationContext.Setup(ctx =>
{
                ctx.EnableInvariantCultureFallback = false;
});`

Do you have any ideas? Looking at the decompiled provider code it looks like it should return null but its not. 

Thanks again
Paul

**Comment by valdisiljuconoks** [comment]
hi,

resource translations follow not only their on configuration (invariant fallback) but also is respecting episerver settings. can you check your episerver localization in web.config file. I'd that one is configured to fallback - it will fallback when you ask for translation.

So essentially - DbLocalizationProvider is just one of the providers in episerver's list. Episerver is asking all providers one by one which has the translation for given resource for given language. If DbLocalizationProvider returns null (for specific language) Episerver will "catch" it and following localization settings will "try" to find translation in next round bit this time using next fallback language.

Overall it's quite complex if you go deeper there.

I'm not sure whether there is option to "check" if translation exists for given language using provider API for Episerver. One trick would be to *not* use `LocalizationService` (Episerver's one) but `LocalizationProvider` (directly from DbLocalizationProvider namespace)..

Please follow up on this. If we are missing this API - think adding would be quite simple.

**Comment by pamiddleton** [comment]
Hi Valdis, 

So I took a further look through your provider code, but unfortunately still can't find a way around this. 
I'll break down the important calls that are made from your provider, through to the localization service itself. 

So an example I am working with currently is a label being used on the cart page:

`string message = new GetTranslation.Query("Cart.Apply", language, false).Execute();`

The language provided to this query is en-US, and I'm specifying no fallbacks (I've also removed fallbacks from my config aswell). 

Your execute method looks fine - it's exactly how I want it to behave - try get the label using the provided culture, and if one isn't found and we enable fallbacks, use the invariant culture:

```
public string Execute(GetTranslation.Query query)
      {
        LocalizationService instance = ServiceLocator.Current.GetInstance<LocalizationService>();
        string stringByCulture = instance.GetStringByCulture(query.Key, query.Language);
        if (string.IsNullOrEmpty(stringByCulture) && instance.FallbackBehavior.HasFlag((Enum) FallbackBehaviors.FallbackCulture) && query.UseFallback && (object.Equals((object) query.Language, (object) instance.FallbackCulture) || object.Equals((object) query.Language.Parent, (object) CultureInfo.InvariantCulture)))
          return this._originalHandler.Execute(new GetTranslation.Query(query.Key, CultureInfo.InvariantCulture, false));
        return stringByCulture;
      }
```

It calls GetStringByCulture in the LocalizationService. GetStringByCulture if I follow it then does the following:

```
CultureInfo actualFallbackCulture = this.GetActualFallbackCulture(fallbackBehavior, culture);
      string localizedString;
      if (this.TryGetStringByCulture(resourceKey, normalizedKey, culture, actualFallbackCulture, out localizedString))
        return localizedString;
      return this.GetMissingFallbackResourceValue(fallbackBehavior, fallback, resourceKey, culture);
```

GetActualFallbackCulture will give us the invariant culture for my culture I've provided (en) and use this in the TrygetStringByCulture call just below it.
So it seems like I will always get a value back from the localization service regardless of if I specify no fallbacks in the provider. 

It seems like an impossible situation using the scenario above - do you know of any other way I can maybe bypass the localization service altogether? It looks like, for EN cultures anyway, I would always get a value back, and have no way to know if the fallback language I've provided has an actual localized label, or if its the result of the invariant culture being used. 

Thanks again,
Paul

**Comment by valdisiljuconoks** [comment]
hi,

sorry for delay here. yes, seems like there is a missing piece to get precise results back when querying for no-existing language translation and explicitly specifying no fallback to be used.

I'll see what we can do here..

**Comment by valdisiljuconoks** [comment]
hi,

couple follow-ups:
* is there a reason why you are using `GetTranslation.Query` and not `LocalizationService`?
* can you paste your `<localization>` element from `<episerver.framework>`?

did I get it correctly that in your case you have to follow fallback languages configured for specific page and not for the framework (via `<>localization>` element in web.config)?

**Comment by pamiddleton** [comment]
Hi, 

I tried both the GetTranslation.Query and LocalizationService aswell to be honest, out of curiosity. But I found both will call the same underlying GetStringByCulture method in the LocalizationService, which causes my issue. 

Here is my localization configuration:
`<localization fallbackBehavior="Echo, MissingMessage">
            <providers>
                <add name="db" type="DbLocalizationProvider.EPiServer.DatabaseLocalizationProvider, DbLocalizationProvider.EPiServer" />
                <add virtualPath="~/Resources/LanguageFiles" name="languageFiles" type="EPiServer.Framework.Localization.XmlResources.FileXmlLocalizationProvider, EPiServer.Framework.AspNet" />
            </providers>
        </localization>`

Yeah, exactly - per page I need to follow fall backs configured if any, and test to see if there is a localized label in that language. 

Thanks, 
Paul

**Comment by valdisiljuconoks** [comment]
ok, and do you need `Echo` & `MissingMessage` fallbacks for the framework?

**Comment by pamiddleton** [comment]
no, its not crucial for us to have them.

**Comment by valdisiljuconoks** [comment]
hi,

sorry for delay here. so basically this functionality is somehow limited due to fact how Episerver is behaving. In order for library to be "good citizen" in the platform, it has to respect Episerver's rules. Which means that library respects what settings Episerver has configured.

So by having

```xml
<episerver.framework>
    <localization fallbackBehavior="Null">
      <providers>
          ....
      </providers>
    </localization>
</episerver.framework>
```

With fallback set to `null` you should be able to receive back `null` when requesting resource translation for missing language:

```csharp
// _provider is injected LocalizationProvider
var r = _provider.GetStringByCulture(() => Class1.JustSimpleResource, new CultureInfo("fr"));
```

**Comment by pamiddleton** [comment]
Hi, 

Sorry for the delay in responding. 
I did try out your suggestion but unfortunately it didn't return null for me when providing an en based culture - so for instance en-US, if I don't have a label configured for en-US it just returns me EN back, so I can never fallback to other EN based languages like en-GB from en-US.
I see your point though - its down to the way in which the localisation service falls back to the invariant culture of the culture you provide to it, internally. 

Time to think of some alternatives! Thanks for your help.

**Comment by valdisiljuconoks** [comment]
That's very strage. I got this behaviour in raw AlloyTech site. Can share sample code if that helps..

**Comment by pamiddleton** [comment]
I guess your example is slightly different to mine in that you requested for FR culture, which is an invariant culture. 
If you test with, for example en-US, having no label configured for en-US, you should see that it will default to EN and pass you back a value for that label instead, because of this line in the localization service:
`CultureInfo actualFallbackCulture = this.GetActualFallbackCulture(fallbackBehavior, culture);`
You may have already tried this though :)

**Comment by valdisiljuconoks** [comment]
it shouldn't matter either you are asking in specific culture (with region) or general. if you do have `Null` set as behavior for the localization service in web.config -> you should get back `null`. Just tested once again..

**Comment by pamiddleton** [comment]
Unfortunately I don't get the same result.
And you have a value for the label in the invariant culture? So EN in this case. 
The only reason I ask is that from what I can tell it boils down to this method:

```
public virtual string GetStringByCulture(string resourceKey, FallbackBehaviors fallbackBehavior, string fallback, CultureInfo culture)
    {
      if (string.IsNullOrEmpty(resourceKey))
      {
        if (fallback != null)
          return fallback;
        if (fallbackBehavior.HasFlag((Enum) FallbackBehaviors.Echo))
          return resourceKey;
        if (fallbackBehavior.HasFlag((Enum) FallbackBehaviors.Null))
          return (string) null;
        Validator.ThrowIfNullOrEmpty(nameof (resourceKey), resourceKey);
      }
      Validator.ThrowIfNull(nameof (culture), (object) culture);
      string[] normalizedKey = this.NormalizeKey(resourceKey);
      CultureInfo actualFallbackCulture = this.GetActualFallbackCulture(fallbackBehavior, culture);
      string localizedString;
      if (this.TryGetStringByCulture(resourceKey, normalizedKey, culture, actualFallbackCulture, out localizedString))
        return localizedString;
      return this.GetMissingFallbackResourceValue(fallbackBehavior, fallback, resourceKey, culture);
    }
```
Which will always look to get the ActualFallbackCulture - which results in EN for a query of en-US for me. 
If you have no value for EN either then it will return null.
I'll test this on Alloys also to make sure I haven't missed anything. 

Thanks again!

**Comment by valdisiljuconoks** [comment]
yes, you are correct. I misunderstood setup. Yes, if you will have no regional culture translation, but there will be one for "parent" culture, you will get that one. actual method "guilty" for this is `protected virtual bool TryGetStringByCulture(...)`

**Comment by valdisiljuconoks** [comment]
however, IMHO trying pretty hard it would be possible to mimic this behavior and replace localization service completely.

**Comment by pamiddleton** [comment]
Yeah, it's proving kind of impossible to do what I need to do. 
It seems a little confusing however that within the localization service it would fallback like this, and kind of ignore our fallback settings we have provided via config. 
Anyway, thank you for your time on this! It seems there is no way around the localization service logic.
