### ISSUE TITLE
DBLocalization seems to prevent xml localization for second culture

### ISSUE THREAD

**Issue by huguesl** [valdisiljuconoks/localization-provider-epi#183]
Using Optimizely CMS 12, Asp.Net Core 6.

We have DBLocalization working fine in both English and French. XML Localization in English also works well as a fallback, however French localization doesn't work. If DBLocalization init code is commented out in Startup.cs, both English and French xml localization works well. 

For some reason, when DBLocalization is used, XML French localization stops working (English xml works fine).

We're trying different configurations of options but nothing seems to get french xml working when DBLocalization is used.

Has anyone run into this?
Thank you

**Comment by valdisiljuconoks** [comment]
Just verified (but with Norwegian language) - it's working as expected.
So here is my setup:
* added XML based localization with

```csharp
services.AddLocalization(options =>
{
    options.ResourcesPath = Path.Combine(_webHostingEnvironment.ContentRootPath, "lang");
});
```

* created new XML file with 2 languages:

```xml
<?xml version="1.0" encoding="utf-8"?>
<languages>
  <language name="Swedish" id="sv">
    <resourcefromxml>
      <prop1>Property 1 from XML file (SV)</prop1>
    </resourcefromxml>
  </language>
  <language name="Norsk" id="no">
    <resourcefromxml>
      <prop1>Property 1 from XML file (NO)</prop1>
    </resourcefromxml>
  </language>
</languages>
```

* used resource in view:

```
@Html.Translate("/resourcefromxml/prop1").ToString()
```

works as expected and shows Norwegian content if browsing in "no" culture:

![image](https://user-images.githubusercontent.com/1767179/207160080-ad4c0ef6-4149-47ea-8639-507418bb1a70.png)

maybe there is something else about your setup that we haven't noticed..
sample code is available in Alloy sandbox: https://github.com/valdisiljuconoks/localization-provider-epi/commit/f62f8d835877a4d60846abf686ae84c7ae5227ad

**Comment by huguesl** [comment]
Thank you for taking the time for this, much appreciated.

If you add DBLocalizationProvider.Episerver and DblocalizationProvider.AdminUI.Episerver to the project and configure them in Startup, does xml localization continue to work as expected for both languages?

**Comment by valdisiljuconoks** [comment]
yes, check out alloy sandbox. `Translate()` returns correct resource text for both languages.

**Comment by huguesl** [comment]
Ok, it might work in our project as well. Where we're running into issues is when using @Html.LabelFor(x => x.Name) along with LocalizedDisplay attributes and other attributes on the properties. Is that supposed to work as well?
