### ISSUE TITLE
Missing in Admin: resources return 404s on integration environment

### ISSUE THREAD

**Issue by benvaltech** [valdisiljuconoks/localization-provider-epi#190]
Working on local, but getting 404 for vue.min.js and other resources on integration
![birkerror](https://user-images.githubusercontent.com/123690222/214952911-0e059524-5bff-4d0a-b0d6-8d1a092de692.png)

![image](https://user-images.githubusercontent.com/123690222/214953032-2761bd94-f834-4dee-ba39-4c452d5f9111.png)

**Comment by valdisiljuconoks** [comment]
Looks like `_content` folder or some other part in the URL triggers request abort. Any fancy Cloudflare setup there?
