### ISSUE TITLE
Not seeing localized variable value in English site - upgrading to CMS 12

### ISSUE THREAD

**Issue by coolgal1980** [valdisiljuconoks/localization-provider-epi#192]
Updated to .NET 6 and installed the latest for Optimizely CMS 12 and updated DBLocalizationProvider nugets and updated startup.cs code to
![image](https://user-images.githubusercontent.com/35546044/222347941-cf61c715-9ce1-4393-b5bc-a0ac24bbd923.png)
![image](https://user-images.githubusercontent.com/35546044/222348025-cc3af8b6-f56b-4264-a2e8-4955db22447f.png)
It doesn't show the value being set in Admin/Localization:
![image](https://user-images.githubusercontent.com/35546044/222348271-108f818d-39a0-4b10-b764-90e0bd7aeabf.png)
It shows whats hardcoded in the code in Translations.Global
![image](https://user-images.githubusercontent.com/35546044/222348360-1527b39b-d1a0-42f7-99e8-31b675f9e5a7.png)
![image](https://user-images.githubusercontent.com/35546044/222348417-9c28f200-aba9-48c7-86a4-6362094aafbf.png)

**Comment by valdisiljuconoks** [comment]
Hi,

How do you output translation in the markup?

**Comment by coolgal1980** [comment]
Here:

[image: image.png]

**Comment by valdisiljuconoks** [comment]
Image is missing

**Comment by coolgal1980** [comment]
I posted images on GitHub. But its this code:
 <div class="col-sm-8 no-margin-bottom">
                    <p class="proxima-nova semi-bold footer-note
no-margin-bottom">
                 *
@Html.Translate(QDX.Models.Translations.Global.AllRightsReserved)         *

                        @Html.Raw(Model.StartPage.AddnlText)
                    </p>
                </div>

**Comment by coolgal1980** [comment]
Also, when I use what examples suggest, I am not able to compile
![image](https://user-images.githubusercontent.com/35546044/222668696-35e4ceeb-48e3-46b9-b046-a19cee898b56.png)

**Comment by coolgal1980** [comment]
![image](https://user-images.githubusercontent.com/35546044/222669117-740b6e60-7c3b-4d21-9778-49b7bead6487.png)

**Comment by valdisiljuconoks** [comment]
Yes, you have to use lambda expression to get translations working. What happens now is that you pass `string` to `Translate()` method as resource key, which does not exist and it fallbacks to just provided resource key - that's why you see hard-coded value as result.

Regarding not being able to compile lambda expression... Do you have `@using DbLocalizationProvider.AspNetCore` at the beginning of .cshtml file?
