### ISSUE TITLE
Possible Performance Issue

### ISSUE THREAD

**Issue by khurramkhang** [valdisiljuconoks/localization-provider-epi#21]
Hi,
 
Have a look at https://world.episerver.com/forum/developer-forum/-Episerver-75-CMS/Thread-Container/2019/4/episerver-cms-mode-page-tree-performance/ 
Today I managed to run a profiler on azure SQL DB and could see
there are thousands and thousands of calls to below SP on loading just editor area

Calls to this SP started at 12:39 and continued fro different items until 12: 45, DB was busy in processing just those request. 

From Chrome, I could see 502 errors for following JS after 4 mins 
EpiServer.shared.js
EPiserver.shell.ui.resources.js

EPiServer editor will not load in result until we recycle app pool. 
The front side will also be effected after the first call to the CMS Editor.

Do you think DBLoaclization is causing this or the way EPiServer.CMS 11.11.2 is using Localization in Editor area.

I upgraded EPiServer.CMS 11.8.0 to 11.11.2
and DbLocalizationProvider.EPiServer from 4.3.3 to 5.5.0

exec sp_executesql N'SELECT 
    [Project2].[Id] AS [Id], 
    [Project2].[ResourceKey] AS [ResourceKey], 
    [Project2].[ModificationDate] AS [ModificationDate], 
    [Project2].[Author] AS [Author], 
    [Project2].[FromCode] AS [FromCode], 
    [Project2].[IsModified] AS [IsModified], 
    [Project2].[IsHidden] AS [IsHidden], 
    [Project2].[C1] AS [C1], 
    [Project2].[Id1] AS [Id1], 
    [Project2].[ResourceId] AS [ResourceId], 
    [Project2].[Language] AS [Language], 
    [Project2].[Value] AS [Value], 
    [Project2].[LocalizationResource_Id] AS [LocalizationResource_Id]
    FROM ( SELECT 
        [Limit1].[Id] AS [Id], 
        [Limit1].[ResourceKey] AS [ResourceKey], 
        [Limit1].[ModificationDate] AS [ModificationDate], 
        [Limit1].[Author] AS [Author], 
        [Limit1].[FromCode] AS [FromCode], 
        [Limit1].[IsModified] AS [IsModified], 
        [Limit1].[IsHidden] AS [IsHidden], 
        [Extent2].[Id] AS [Id1], 
        [Extent2].[ResourceId] AS [ResourceId], 
        [Extent2].[Language] AS [Language], 
        [Extent2].[Value] AS [Value], 
        [Extent2].[LocalizationResource_Id] AS [LocalizationResource_Id], 
        CASE WHEN ([Extent2].[Id] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
        FROM   (SELECT TOP (1) 
            [Extent1].[Id] AS [Id], 
            [Extent1].[ResourceKey] AS [ResourceKey], 
            [Extent1].[ModificationDate] AS [ModificationDate], 
            [Extent1].[Author] AS [Author], 
            [Extent1].[FromCode] AS [FromCode], 
            [Extent1].[IsModified] AS [IsModified], 
            [Extent1].[IsHidden] AS [IsHidden]
            FROM [dbo].[LocalizationResources] AS [Extent1]
            WHERE [Extent1].[ResourceKey] = @p__linq__0 ) AS [Limit1]
        LEFT OUTER JOIN [dbo].[LocalizationResourceTranslations] AS [Extent2] ON [Limit1].[Id] = [Extent2].[ResourceId]
    )  AS [Project2]
    ORDER BY [Project2].[Id] ASC, [Project2].[C1] ASC',N'@p__linq__0 varchar(8000)',@p__linq__0='/contenttypes/MYBLOCKSNAME/description'

**Comment by valdisiljuconoks** [comment]
do you see the same call to db for the same resource key? it should be cached after 1st call. I'll try this out in sandbox.

**Comment by khurramkhang** [comment]
There were 12 calls for same key as N'@p__linq__0 varchar(8000)',@p__linq__0='/contenttypes/HomePage/properties/SearchPage/caption'

few in following time
12:40 
12:41:45
12:42:18
12:42:50

Copied two queries from different time

exec sp_executesql N'SELECT 
    [Project2].[Id] AS [Id], 
    [Project2].[ResourceKey] AS [ResourceKey], 
    [Project2].[ModificationDate] AS [ModificationDate], 
    [Project2].[Author] AS [Author], 
    [Project2].[FromCode] AS [FromCode], 
    [Project2].[IsModified] AS [IsModified], 
    [Project2].[IsHidden] AS [IsHidden], 
    [Project2].[C1] AS [C1], 
    [Project2].[Id1] AS [Id1], 
    [Project2].[ResourceId] AS [ResourceId], 
    [Project2].[Language] AS [Language], 
    [Project2].[Value] AS [Value], 
    [Project2].[LocalizationResource_Id] AS [LocalizationResource_Id]
    FROM ( SELECT 
        [Limit1].[Id] AS [Id], 
        [Limit1].[ResourceKey] AS [ResourceKey], 
        [Limit1].[ModificationDate] AS [ModificationDate], 
        [Limit1].[Author] AS [Author], 
        [Limit1].[FromCode] AS [FromCode], 
        [Limit1].[IsModified] AS [IsModified], 
        [Limit1].[IsHidden] AS [IsHidden], 
        [Extent2].[Id] AS [Id1], 
        [Extent2].[ResourceId] AS [ResourceId], 
        [Extent2].[Language] AS [Language], 
        [Extent2].[Value] AS [Value], 
        [Extent2].[LocalizationResource_Id] AS [LocalizationResource_Id], 
        CASE WHEN ([Extent2].[Id] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
        FROM   (SELECT TOP (1) 
            [Extent1].[Id] AS [Id], 
            [Extent1].[ResourceKey] AS [ResourceKey], 
            [Extent1].[ModificationDate] AS [ModificationDate], 
            [Extent1].[Author] AS [Author], 
            [Extent1].[FromCode] AS [FromCode], 
            [Extent1].[IsModified] AS [IsModified], 
            [Extent1].[IsHidden] AS [IsHidden]
            FROM [dbo].[LocalizationResources] AS [Extent1]
            WHERE [Extent1].[ResourceKey] = @p__linq__0 ) AS [Limit1]
        LEFT OUTER JOIN [dbo].[LocalizationResourceTranslations] AS [Extent2] ON [Limit1].[Id] = [Extent2].[ResourceId]
    )  AS [Project2]
    ORDER BY [Project2].[Id] ASC, [Project2].[C1] ASC',N'@p__linq__0 varchar(8000)',@p__linq__0='/contenttypes/HomePage/properties/SearchPage/caption'




exec sp_executesql N'SELECT 
    [Project2].[Id] AS [Id], 
    [Project2].[ResourceKey] AS [ResourceKey], 
    [Project2].[ModificationDate] AS [ModificationDate], 
    [Project2].[Author] AS [Author], 
    [Project2].[FromCode] AS [FromCode], 
    [Project2].[IsModified] AS [IsModified], 
    [Project2].[IsHidden] AS [IsHidden], 
    [Project2].[C1] AS [C1], 
    [Project2].[Id1] AS [Id1], 
    [Project2].[ResourceId] AS [ResourceId], 
    [Project2].[Language] AS [Language], 
    [Project2].[Value] AS [Value], 
    [Project2].[LocalizationResource_Id] AS [LocalizationResource_Id]
    FROM ( SELECT 
        [Limit1].[Id] AS [Id], 
        [Limit1].[ResourceKey] AS [ResourceKey], 
        [Limit1].[ModificationDate] AS [ModificationDate], 
        [Limit1].[Author] AS [Author], 
        [Limit1].[FromCode] AS [FromCode], 
        [Limit1].[IsModified] AS [IsModified], 
        [Limit1].[IsHidden] AS [IsHidden], 
        [Extent2].[Id] AS [Id1], 
        [Extent2].[ResourceId] AS [ResourceId], 
        [Extent2].[Language] AS [Language], 
        [Extent2].[Value] AS [Value], 
        [Extent2].[LocalizationResource_Id] AS [LocalizationResource_Id], 
        CASE WHEN ([Extent2].[Id] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
        FROM   (SELECT TOP (1) 
            [Extent1].[Id] AS [Id], 
            [Extent1].[ResourceKey] AS [ResourceKey], 
            [Extent1].[ModificationDate] AS [ModificationDate], 
            [Extent1].[Author] AS [Author], 
            [Extent1].[FromCode] AS [FromCode], 
            [Extent1].[IsModified] AS [IsModified], 
            [Extent1].[IsHidden] AS [IsHidden]
            FROM [dbo].[LocalizationResources] AS [Extent1]
            WHERE [Extent1].[ResourceKey] = @p__linq__0 ) AS [Limit1]
        LEFT OUTER JOIN [dbo].[LocalizationResourceTranslations] AS [Extent2] ON [Limit1].[Id] = [Extent2].[ResourceId]
    )  AS [Project2]
    ORDER BY [Project2].[Id] ASC, [Project2].[C1] ASC',N'@p__linq__0 varchar(8000)',@p__linq__0='/contenttypes/HomePage/properties/SearchPage/caption'

**Comment by valdisiljuconoks** [comment]
hi,

testing this scenario locally and seems I can't reproduce this. indeed - on 1st call for the resources, this method might take longer as library would need to go to the database and look for key existence there (resource with that key might be just "kicked -out" from the cache). but provider stores these "empty hits" in cache and next time somebody will ask for non-existing resource key - lookup in memory should be performed (instead of query against db).

is you install latest episever dev tools and go to cache view -> do you see those resource keys inside cache items list? wondering - maybe there is something that is throwing out cache keys!?

**Comment by khurramkhang** [comment]
I am also not able to reproduce the scenario locally. On production also The issue appears about 6/7 days after the release. and resolves on application recycle for the next 6/7 days. I was able to replicate that issue on one of the test environment where the last release was more than a week. 

I also expect the same that there is something that is throwing cache keys. Wondering if this possible that provider caching keys ONLY on-site initialization and if that cache is expiring after a week this is never set. Does the provider have some cache eviction policy?

**Comment by valdisiljuconoks** [comment]
there is no policy around eviction for the cache keys. it relies on defaults from Episerver CacheManager - https://github.com/valdisiljuconoks/localization-provider-epi/blob/master/src/DbLocalizationProvider.EPiServer/EPiServerCacheManager.cs

It might be so that after a week of running time, memory pressure is present and runtime starts to panic.
Can you check also what's happening in other areas of the app.

I really would like to solve this out if it's provider issue.

**Comment by khurramkhang** [comment]
I will setup developer tools and will investigate further, I will keep you updated.

**Comment by khurramkhang** [comment]
https://ibb.co/Sc6ZQwj
is this what we will expect?

**Comment by valdisiljuconoks** [comment]
-1 might mean that resource actually does not exist or deserialization of cached object failed. can you check those resource keys (after `_` symbol). do you really have them in database or these are "mishits". because for performance reasons package is also storing "mishits" which means that library knows that this resource does not exist and there is no reason to go to db.

also I could image that there are couple of operations that cause cache clearance - for example resource import via admin ui. maybe that's playing some role here as well...

**Comment by valdisiljuconoks** [comment]
@khurramkhang how is going with this issue?

**Comment by khurramkhang** [comment]
Sorry for the late reply, I had been trying to reproduce But not able to replicate
