### ISSUE TITLE
JSON import of new resource not working

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#22]
If I create a new resource in AdminUI on System A and I fill it in two languages, then I export in JSON, then I try to import on System B, it imports only in English. When importing, it does not even display the columns for the other language. In JSON file it seems to be correct:
  {
    "id": 1987,
    "resourceKey": "/zsolttest",
    "modificationDate": "2019-04-30T14:02:14.99Z",
    "author": "_ext_zsoltne_adm",
    "isModified": true,
    "translations": [
      {
        "id": 16936,
        "resourceId": 1987,
        "language": "de",
        "value": "new"
      },
      {
        "id": 16937,
        "resourceId": 1987,
        "language": "en",
        "value": "resource"
      }
    ]
  }

Package DbLocalizationProvider.AdminUI.EPiServer 5.5.1.

I cannot reproduce right now, but when I tried to export 2000 migrated resources on System A and tried to import it on System B, which was completely empty, there was no translations imported, only the resource entries themselves.

In both cases a workaround is to reimport the file and accept the "updates".
I am not sure if it has anything to do with legacy and migrated resources.

**Comment by valdisiljuconoks** [comment]
hi,

are the same languages enabled in both systems?

**Comment by nzsb** [comment]
hi,
yes, for my test it is german and english. I guess otherwise the update would not work either.

**Comment by valdisiljuconoks** [comment]
any specific/weird resource key names? or just xpath?

**Comment by valdisiljuconoks** [comment]
found an issue. this affects only new resources. fixing..

**Comment by nzsb** [comment]
No special name, just xpath, alphabetical with foward slash like in the json.
