### ISSUE TITLE
Export includes deactivated language. Fails to import.

### ISSUE THREAD

**Issue by geitsund** [valdisiljuconoks/localization-provider-epi#28]
I'm working on a solution where we have several languages installed. One of these languages have at one point been deactivated.

If we now do an export the deactivated language is included in the export, but when we try to do an import we get an error saying _"Importing language 'se' is not available in current EPiServer installation"_.

We are currently running version 5.4.0

**Comment by valdisiljuconoks** [comment]
hi,

thanks for reporting. this is definitely a bug. export should also respect deactivated languages.
will be part of upcoming v5.7
