### ISSUE TITLE
Version 5.4.0 makes edit mode slow

### ISSUE THREAD

**Issue by Sigve-Fast** [valdisiljuconoks/localization-provider-epi#31]
I had version 5.4.0 installed in a episerver 11.11.2 solution and it it took about 5 minutes just to enter edit mode. Downgraded to version 5.0.0 and now it's fast again.

I only experienced this error locally on my developer machine. In test and production everything was good. I had the site running in IIS Express and I am working through a VPN to my office so the database connection is a little bit slow, but not that slow.

In the event viewer log a got a lot of this error. _"The WebSocket instance cannot be used for communication because it has been transitioned into an invalid state."_

I have these nugets installed:
LocalizationProvider
LocalizationProvider.Abstractions
LocalizationProvider.AspNet
LocalizationProvider.EPiServer
LocalizationProvider.AdminUI.EPiServer

**Comment by Sebbe** [comment]
@Sigve-Fast How is your fallback set in episerverframework section?
