### ISSUE TITLE
Episerver Admin UI JSON import does not invalidate cache in Load Balanced environment

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#33]
Hi,

If a JSON file is imported in Admin UI, the Episerver Cache is not invalidated and other servers in a load balanced environment does not have the latest resources. Workaround is to restart all other servers.
I have not validated if XLIFF import have the same issue.
Cache will be invalidated if I change a value im Admin UI manually.

Using version 5.6.0 (sorry I did not have the time to test with 5.7.0).

Thanks in advance!

**Comment by valdisiljuconoks** [comment]
is lib working for you at all?? :)

**Comment by nzsb** [comment]
We are using it very heavily :-)
Client is happy and I am happy with it!
