### ISSUE TITLE
DbLocalizationProvider.MigrationTool does not create SQL for empty resources

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#34]
Hi,

I used the following command to create an SQL script from our XML resources:

packages\DbLocalizationProvider.MigrationTool.5.6.0\tools\DbLocalizationProvider.MigrationTool.exe -s MyWebApplication -e --resourceDirectory Lang -x

And a few weeks later I noticed that for resources, where in all languages there was no value defined, the tool did not create any entry. So we XML looks like this:
<myResource />
There is no entry created.
For resources where at least one language has a non-empty value, were exported.

For me it is not an issue anymore. I already migrated and only 3 resources were missing, I added them manually.
Thanks.

**Comment by valdisiljuconoks** [comment]
hi,

can you paste fragment from XML file once again?

**Comment by nzsb** [comment]
Hi,

XML:
`<myResource />`
