### ISSUE TITLE
JsResourceHandler doesn't use fallbacklanguage

### ISSUE THREAD

**Issue by Sebbe** [valdisiljuconoks/localization-provider-epi#37]
Hi,

In our episerverframework config we have a setup like this:

```
<localization fallbackBehavior="Echo, MissingMessage, FallbackCulture" fallbackCulture="en-GB">
    <providers>
      <add name="db" type="DbLocalizationProvider.EPiServer.DatabaseLocalizationProvider, DbLocalizationProvider.EPiServer" />
    </providers>
  </localization>
```

and in out initilizer I have added this code (just to test if it works, but it doesn't change the outpout

```csharp
ConfigurationContext.Setup(ctx =>
{
    ctx.DefaultResourceCulture = new CultureInfo("en-GB");
});
```

And the epi language settings, these is the settings:
![bilde](https://user-images.githubusercontent.com/814625/61638155-1c859100-ac99-11e9-9bfc-ab1bdbab042e.png)

In epi localization mode I can see these translations
![bilde](https://user-images.githubusercontent.com/814625/61637395-bcdab600-ac97-11e9-8dd7-1059f3d21396.png)

When I look at the translation for the key "Norrona.Commerce.Framework.Translations.Profile.BetaTesterLabel" in english in the jsl10n, then I see it fine (because it is filled out)
But when I go to the norwegian jsl10n, then it is not in the resource at all

Live example urls here:
English: https://www.norrona.com/jsl10n/Norrona.Commerce.Framework.Translations.Profile?lang=en-GB
Norwegian:  https://www.norrona.com/jsl10n/Norrona.Commerce.Framework.Translations.Profile?lang=nb-NO

This is for the latests packages (5.7.1)

if I add this code instead
```csharp
ConfigurationContext.Setup(ctx =>
{
    ctx.DefaultResourceCulture = CultureInfo.InvariantCulture;
    ctx.EnableInvariantCultureFallback = true;
});

 UiConfigurationContext.Setup(ctx => { ctx.ShowInvariantCulture = true; });
```

Then it kinda works, I get the translation in english, but the InvariantCulture is not possible to edit, if it was possible to edit then that would have been a solution for us

**Comment by valdisiljuconoks** [comment]
thanks for detailed description! have you ever got provider working ?? :troll:

**Comment by Sebbe** [comment]
lucky enough yes ;) Just not the JsResourceHandler

So, will you have a fix to tomorrow? :troll:

**Comment by Sebbe** [comment]
Thanks for starting working on this right away.
I found a workaround for now that works for us (still need to confirm the fix with my boss)

The fix is to do this:
@Html.GetTranslations(typeof(Translations), "en-GB")
@Html.GetTranslations(typeof(Translations))

It is still wrong as we have setup that norwegian should be the fallback language for sweden, but at least we don't get an "undefined" error anymore, and actual translation. and in english it gets loaded twice, but still better then no translation :D

Thanks for the help, have a good day

**Comment by valdisiljuconoks** [comment]
however, there is a catch. this workaround is sort of working - will overwrite (deep merge), but.. JsClientResource will (and have to) follow the same fallback rules that is configured for built-in Episerver localization service (`<localization>` element). Language specific fallbacks are effective only for *content* and not for resources (XML file based ones for example). So it still will not be possible to configure fallback for different languages to use different fallback languages.

This is planned feature in v6.0 -> to eliminate this Episerver localization service fallback language limitation and give possibility for developers to configure whatever settings make sense for resources.

**Comment by valdisiljuconoks** [comment]
Would you still want to try out *proper* fix (preview of v5.7.4) or you are good with this workaround? I will be able to send you a preview after couple hours..

**Comment by valdisiljuconoks** [comment]
and also - in order to get correct behavior of the fallbacks - you need to change order of behaviors to:

```
<localization fallbackBehavior="FallbackCulture, Echo, MissingMessage" fallbackCulture="en-GB">
```

`Echo` and `MissingMessage` -> you have to check with your requirements how exactly missing resource translations should behave in your site..

**Comment by Sebbe** [comment]
Yes, a proper fix is the best and I will be happy to test it out :)

**Comment by Sebbe** [comment]
Tried it out now, and it doesn't looke like it works, but thanks anyway. Looking forward to v6.0!
Thanks for your great effort

**Comment by valdisiljuconoks** [comment]
I do have a working sample with 5.7.4 maybe we have some specific difference?

**Comment by Sebbe** [comment]
Maybe, I may have done something wrong with the preview packages you sent me too. I will just wait for the offical packages and try again then :)

**Comment by valdisiljuconoks** [comment]
v6.0 might not come so quickly..

**Comment by Sebbe** [comment]
I ment I will wait for the 5.7.4 package in the official nuget reporsitory as I may have done something wrong when I installed it localy :)
I understand that v6.0 will take time and not be here, but for now we at least have a backup solution even if 5.7.4 doesn't work

**Comment by valdisiljuconoks** [comment]
if 5.7.4 will not solve your issue, I'll retire and will spend all days picking mushrooms in forest..

**Comment by Sebbe** [comment]
Thanks, I will test during the week, right now I'm testing if 
`<localization fallbackBehavior="FallbackCulture, Echo, MissingMessage" fallbackCulture="en-GB">`
makes the edit mode slow... because suddenly the whole epi edit mode is slow, and I think I have backtracked it to that change

It may have something to do with issue #31 though

**Comment by valdisiljuconoks** [comment]
might be. please run SQL profiler to check details under the hood. might be cache misses all the time..

**Comment by Sebbe** [comment]
It only happens in production, lovaly it is fine... so any idea how i can check in production? Never used sql profiler 😂

**Comment by valdisiljuconoks** [comment]
DXC?

**Comment by Sebbe** [comment]
On-prem as it is much cheaper, so i have access to the servers

**Comment by Sebbe** [comment]
Okey, Learned how to run SQL profiler I think :')

I see a lot of there
`exec sp_executesql N'SELECT 
    [Project2].[Id] AS [Id], 
    [Project2].[ResourceKey] AS [ResourceKey], 
    [Project2].[ModificationDate] AS [ModificationDate], 
    [Project2].[Author] AS [Author], 
    [Project2].[FromCode] AS [FromCode], 
    [Project2].[IsModified] AS [IsModified], 
    [Project2].[IsHidden] AS [IsHidden], 
    [Project2].[C1] AS [C1], 
    [Project2].[Id1] AS [Id1], 
    [Project2].[ResourceId] AS [ResourceId], 
    [Project2].[Language] AS [Language], 
    [Project2].[Value] AS [Value], 
    [Project2].[LocalizationResource_Id] AS [LocalizationResource_Id]
    FROM ( SELECT 
        [Limit1].[Id] AS [Id], 
        [Limit1].[ResourceKey] AS [ResourceKey], 
        [Limit1].[ModificationDate] AS [ModificationDate], 
        [Limit1].[Author] AS [Author], 
        [Limit1].[FromCode] AS [FromCode], 
        [Limit1].[IsModified] AS [IsModified], 
        [Limit1].[IsHidden] AS [IsHidden], 
        [Extent2].[Id] AS [Id1], 
        [Extent2].[ResourceId] AS [ResourceId], 
        [Extent2].[Language] AS [Language], 
        [Extent2].[Value] AS [Value], 
        [Extent2].[LocalizationResource_Id] AS [LocalizationResource_Id], 
        CASE WHEN ([Extent2].[Id] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
        FROM   (SELECT TOP (1) 
            [Extent1].[Id] AS [Id], 
            [Extent1].[ResourceKey] AS [ResourceKey], 
            [Extent1].[ModificationDate] AS [ModificationDate], 
            [Extent1].[Author] AS [Author], 
            [Extent1].[FromCode] AS [FromCode], 
            [Extent1].[IsModified] AS [IsModified], 
            [Extent1].[IsHidden] AS [IsHidden]
            FROM [dbo].[LocalizationResources] AS [Extent1]
            WHERE [Extent1].[ResourceKey] = @p__linq__0 ) AS [Limit1]
        LEFT OUTER JOIN [dbo].[LocalizationResourceTranslations] AS [Extent2] ON [Limit1].[Id] = [Extent2].[ResourceId]
    )  AS [Project2]
    ORDER BY [Project2].[Id] ASC, [Project2].[C1] ASC',N'@p__linq__0 varchar(8000)',@p__linq__0='/contenttypes/ProductRowBlock/properties/LastWeek/help'`
where the last part `/contenttypes/ProductRowBlock/properties/LastWeek/help` usually is diffrent

Not sure if that will help at all though. Looks like the query goes quick, but guess if it is many it may have some performance issues?

**Comment by valdisiljuconoks** [comment]
yeah, this seems like CMS is building resource cache at startup.. hmmm
