### ISSUE TITLE
Typescanner creates resources multiple times in load balanced environment

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#38]
Hi,

I could not test this issue myself, but in an environment where there were no resources yet created and DbLocalizationProvider tried to create all 2051 resources defined in code, created 141 resources two times and 6 resources even three times. We have 6 servers, all were started paralelly.
I was hoping maybe you have an idea on this, is the registration load-balance safe? (Apparently there is no unique constraint on ResourceKey)
Using version 5.6.0 with Episerver.

Thanks!

**Comment by valdisiljuconoks** [comment]
hi,

indeed, it is tricky. will check where constraints gone. are you on dxc? this is gray area with almost no investment..

**Comment by nzsb** [comment]
Not dxc, but there are multiple servers. Easy workaround could be maybe that only the server configured as event replication master can create the new resources - just an idea.

**Comment by valdisiljuconoks** [comment]
yes, there has to be some sort of sync primitive in between the servers. will need to look for something.. I like idea how webjobs and az functions do it - via storage blob blocking feature.

**Comment by valdisiljuconoks** [comment]
hi,

can you verify what indexes you do have on resource table?

https://github.com/valdisiljuconoks/localization-provider-aspnet/blob/master/src/DbLocalizationProvider.AspNet/LanguageEntities.cs#L56 should do the trick

```
.HasColumnAnnotation(IndexAnnotation.AnnotationName,
                     new IndexAnnotation(new IndexAttribute("IX_ResourceKey", 1)
                                         {
                                             IsUnique = true
                                         }));
```

**Comment by nzsb** [comment]
Hi,

I only have the clustered index for the primary key on the resource table,
nothing else.
This new index IX_ResourceKey should work, thanks!

Regards,
Zsolt
