### ISSUE TITLE
JSON import creates NULL entries in database for IsModified=0 resources, then next startup fails with a NullReferenceException

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#39]
Hi,

Me again :-)
Using version 5.6.0.
When having two resources with translation in "en" and "de" in database and doing an JSON import with a file with following contents:
-resource1 with new translation "nl"
-resource2 (which still has IsModified = 0 in database) with new translation "fr"

In preview shown correctly, that resource1 has "nl" as new change, resource2 has "fr" as new change. Let's accept both updates.

Now if we check in database, for resource2 (where IsModified was 0) a new LocalizationResourceTranslation for "nl" gets written, although there was no change there which seems very strange (problem nr. 1). Other changes are OK.

The problem is by next application startup, for some reason it detects a change and tries to do an update, but it throws a NullReferenceException in ResourceSynchronizer.AddTranslationScript() at line:
        if (resourceTranslation.Value.Equals(resource.Translation))
because resourceTranslation.Value is null (problem nr. 2).

It happens only with new resources, so as a workaround we set IsModified to 1 for all resources, it seems to be working that way.

Could you look at this?
Is it possible to have some logging if something like this happens? On production we only have access to logs, not for servers.
Thanks!

**Comment by valdisiljuconoks** [comment]
hi :)

think I've seen your name already :)) (no offense).
so, is it that we have bug that is overwriting other resource translations? resource1 and resource2 have different resource keys, right?

**Comment by nzsb** [comment]
Yes, resource1 and resource2 have different resource keys.
It is not overwriting anything, it is just creating unnecessary NULL entry where there was no change display in Preview - resource2 had no translation for "nl" before the import, in the import file it also had no change, but after the import there is a new LocalizationResouceTranslation entry with Value = NULL in the database, which causes then problem nr. 2.

**Comment by valdisiljuconoks** [comment]
gotcha

**Comment by valdisiljuconoks** [comment]
yes, that's nasty bug out there.. :( working on fix for this

**Comment by valdisiljuconoks** [comment]
give it a try in 5.7.2

**Comment by nzsb** [comment]
Thanks for the quick fix!
When do you plan to release version 5.7.2, we plan to include it in our next release.

**Comment by valdisiljuconoks** [comment]
It's already on the way to the feed. Keep an eye on it.

**Comment by nzsb** [comment]
Works like a charm, thanks a lot!
