### ISSUE TITLE
JsResourceHandler doesn't invalidate cache

### ISSUE THREAD

**Issue by dvMasiuk** [valdisiljuconoks/localization-provider-epi#4]
Hi there!
It seems JsResourceHandler doesn't remove entries from cache.
JsResourceHandler uses CacheKeyHelper.GenerateKey to inset entries, but here
https://github.com/valdisiljuconoks/localization-provider-epi/blob/master/src/DbLocalizationProvider.EPiServer.JsResourceHandler/JsResourceCacheInvalidationModule.cs#L34
'existingKey' is just a substring of the cache key hence CacheManager cannot remove entries.

**Comment by valdisiljuconoks** [comment]
good catch

**Comment by valdisiljuconoks** [comment]
out on nuget feed. wait for 4.3.5
