### ISSUE TITLE
JSON import of empty resource gets ignored

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#41]
Hi,

Me again - our testers started testing :-)

If in source system in Admin UI for one resource you delete the value, then do a JSON export, and on target system do an import, the change is not picked up at all.
We have a few resources where the customer in the past decided not to display anything, so this can happen to us.

Another (similar, but a bit unlikely) case that in source system in Admin UI do the following changes for one resource:
-in English make same changes (Text1 -> Text2)
-in German delete the value (Text1 -> "")
Export, then import on target system. Only the change in German gets imported, empty text gets ignored again.

Using version 5.7.3.

Thanks!

**Comment by valdisiljuconoks** [comment]
Hi,

By "removing" - are you referring to "delete" of the translations or setting its value to empty string?

**Comment by nzsb** [comment]
I mean setting the value of a resource of a specific language to empty in Admin UI, so that afterwards a red "Empty" will be displayed.

**Comment by valdisiljuconoks** [comment]
This is where deadline driven / spare time project leads you ;) Export/Import hasn't been main focus for the developer of the LocalizationProvider library..

**Comment by nzsb** [comment]
I know I report a few issues, but my intention was only to increase the quality, that is why I reported this one as well, I hope you don't mind :-)

**Comment by valdisiljuconoks** [comment]
no problem, not all. it's perfect that somebody is kicking bugs out..

**Comment by nzsb** [comment]
Hi Valdis,

I tried this with version 5.7.4 and the issue is still there.
Maybe there is some misunderstanding, let me try to formulate the issue more clearly.

I have a resource MyChangeResource, translations for German and English.
If I export JSON now, it will be the following:

  {
    "id": 887,
    "resourceKey": "MyChangeResource",
    "modificationDate": "2019-06-14T15:36:00Z",
    "author": "migration-tool",
    "fromCode": true,
    "isModified": true,
    "isHidden": false,
    "translations": [
      {
        "id": 24044,
        "resourceId": 887,
        "language": "",
        "value": "Ändern"
      },
      {
        "id": 24044,
        "resourceId": 887,
        "language": "de",
        "value": "Ändern"
      },
      {
        "id": 11970,
        "resourceId": 887,
        "language": "en",
        "value": "Change"
      }
    ]
  },

Then on source system I remove the translation for German (with the Trash Button), red "empty" will appear in AdminUI.
If I now do a JSON Export, it is not in the file:

  {
    "id": 887,
    "resourceKey": "MyChangeResource",
    "modificationDate": "2019-06-14T15:36:00Z",
    "author": "migration-tool",
    "fromCode": true,
    "isModified": true,
    "isHidden": false,
    "translations": [
      {
        "id": 24044,
        "resourceId": 887,
        "language": "",
        "value": "Ändern"
      },
      {
        "id": 11970,
        "resourceId": 887,
        "language": "en",
        "value": "Change"
      }
    ]
  },

If now I do an import on target system, this change will not be imported.

**Comment by valdisiljuconoks** [comment]
oh, now I got it ;) sorry for misunderstanding.. but anyways - I fix other bug that was on the same (similar) path.

about this - hmm, not quite sure how to solve it properly, as delete button really removes the translation and it's gone forever. Meaning that it will not appear in export file. At least - not for now. Workaround is to set value to empty translation..

**Comment by nzsb** [comment]
Sorry for the late answer, github stopped to notify me about new posts and I completely forgot about this :-)
I did not expect that there is a difference between setting to empty vs. using delete button, but indeed, this workaround works!
Is it possible to hide the delete translation button somehow, then we are safer, in our case we never need that delete button.

**Comment by valdisiljuconoks** [comment]
If you would create new issue – I’ll make sure it lands in next minor version :)


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nzsb** [comment]
great, thanks!

**Comment by nzsb** [comment]
Fix is working great (with not using the delete button), thanks!
