### ISSUE TITLE
Episerver Admin UI JSON import does not invalidate cache in Load Balanced environment

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#46]
Hi!

This is very similar to issue #33 

If a JSON file is imported in Admin UI, occasionally the Episerver Cache is not invalidated and frontoffice servers in a load balanced environment does not have the updated resource. 

The issue seems to be always specific to selected resource key. The first few imports update the cache on other servers for the selected resource key, but after that for the particular resource key it is broken (for that lifetime of application pool on the frontoffice server), although in the same import process I update multiple resources and an other one gets refreshed on the frontoffice servers.
I checked in HttpContext.Cache the LocalizationResource object is the old one until a restart for a resource key which is not getting updated on the front office server, so for some reason the cache on Frontoffice is not getting updated.
I am not doing anything fancy, just appended a number at the end of a translation and counting it up. The resource is bound with code.
Changes in CMS getting synced and if I try changing another resource key it works.

Cache will be always correctly invalidated if I change a value in Admin UI manually, I could not reproduce the problem there.
Sorry I cannot give you more specific details, I tried to looked at the code but I could not find anything - if you need me to run some tests, let me know.

Good news is - our testers have finished testing the import for the current version :-)

Using version 5.7.3

Thanks in advance!

**Comment by valdisiljuconoks** [comment]
Hi,

Sorry for delay here. It's a bit hetic. Think this might need to wait till v6.0..

**Comment by nzsb** [comment]
No problem. I am sure of that, looks also complicated. Let me know if I can run some tests for you.

**Comment by nzsb** [comment]
Hi, I took a look at the code and I have a suspect, which looks easy to fix.

So for Updates directly in AdminUI, Cache invalidation is working and done in DbLocalizationProvider.AspNet.Commands.CreateOrUpdateTranslationHandler, the following will be called directly: ConfigurationContext.Current.CacheManager.Remove(CacheKeyHelper.BuildKey(command.Key));

But for updates done in JSON Import cache invadation is in DbLocalizationProvider.AspNet.Cache.ClearCacheHandler:

				if (cacheManager.Get(current) != null)
				{
					cacheManager.Remove(current);
				}

I suspect the problem is here that Get() checks only the local cache, and if the key is not (yet) loaded, Remove() will not be called.
This could be why the problem is sporadic and why Update directly in UI works. If I check Episerver RemoteCacheSynchronization decompiled code, it confirms my suspection, Get reads only local cache, but Remove removed from local and from remote:

    public object Get(string key)
    {
      return this._localCache.Get(key);
    }

    public void Remove(string key)
    {
      this.RemoveLocal(key);
      this.RemoveRemote(key);
    }

So I think the fix is as easy as in DbLocalizationProvider.AspNet.Cache.ClearCacheHandler to remove the "if (cacheManager.Get(current) != null)" check. Does it make sense, can it be done in some next version?

**Comment by valdisiljuconoks** [comment]
hold my beer...

**Comment by valdisiljuconoks** [comment]
need to get some time between rush hours with current project...

**Comment by nzsb** [comment]
Thanks, this one is also working great!
