### ISSUE TITLE
Admin UI isn’t translated.

### ISSUE THREAD

**Issue by jonascarlbaum** [valdisiljuconoks/localization-provider-epi#47]
Hi Valdis!

Great stuff, just tried it out and I really like it.
I did setup main plug-in, admin UI-plug-in and js/Ajax plug-in as instructed in documentation on a new EPi 11 site.

The admin UI isn’t translated, see screenshot:
![14CA720B-8E66-475B-A007-D5F7CDD7B1B1](https://user-images.githubusercontent.com/392041/65079202-e9ad0000-d99e-11e9-9b22-396601263a7a.png)

I wonder if it’s as simple as an extra space in an import-statement in view?

![26498619-D5A0-4007-88C7-959DFD5BEE44](https://user-images.githubusercontent.com/392041/65079049-9cc92980-d99e-11e9-8e5c-566725aeb082.png)

Or might I have missed something during install/setup?

**Comment by valdisiljuconoks** [comment]
Hej,

Thanks! I've seen this bug before, and if remember correctly it was related with current culture (I see they it's "sv") and fallback disabled.

Can you play around those settings to see if that changes the situation?

**Comment by jonascarlbaum** [comment]
Yep, that might be it. 

And that also sounds related to another issue I had today. Where we call the API with `lang=sv`, we want to fallback to `en`. We want the default translation from code to be in english. We are inspired by and adapted the `music festival Vue-SPA` and users have their language settings outside EPi, a custom CRM-DB we might call it, so selected language and language on viewed page doesn’t always match, not yet anyway. Right now the Vue-components breaks if translation is missing, so if we could get fallback-values for non-translated properties it would only be a swenglish site instead of broken and we don’t have to implement fallback in Vue-code... 😉😂

I suspected our language settings was the issue, but also thought we might need some more configuration for non-standard fallback handling in Ajax-requests and responses.

**Comment by jonascarlbaum** [comment]
So, I’ll probably play around a bit tomorrow. 👍

**Comment by valdisiljuconoks** [comment]
It boils down to how epi is configured and how provider is configured. Seek for samples in sandbox projects in repo. And - https://twitter.com/tech_fellow/status/1173209379178504192?s=19

**Comment by jonascarlbaum** [comment]
Yeah, one idea I had was to fetch in english first and then do something like `Object.assign(fallbackResource, currentResource)`. Guess I have to deal with deep nesting issues though, but something like that anyway might solve that fallback issue if nothing else does... 👍😉

**Comment by valdisiljuconoks** [comment]
btw, deep merge is already solved in JSON endpoint. Look for `deepmerge.js` request ;)

**Comment by jonascarlbaum** [comment]
You mean when using the `script`-syntax they will deep merge in `window`-scope-variable?

The `ajax`-calls I do means I need to handle it myself, like to use `deepmerge` npm package or similar, I guess — or was I missing something!? 😉

**Comment by valdisiljuconoks** [comment]
you can call multiple times to get json translations, all of then are deep merged into window variable, yes. so you can use script already included in the package :) I'm using deep merge, but it's just embedded into provider dll

**Comment by jonascarlbaum** [comment]
Guess it was something about that. We fixed some settings etc. and now everything is translated _(I ended up doing the fallback/merge in backend using `GetAllResourcesHandler` and `GetAllResources`-query and iterating, so I could serve exactly what I wanted on both server rendered json and ajax-fetched)_... ;)
