### ISSUE TITLE
Fallback to invariant even if resource is defined as an empty string

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#54]
Hi,

It has been a while since our testers found something :-)

I am using Fallback to invariant setting:
                ctx.EnableInvariantCultureFallback = true;

If I have a resource where there are the following translations:
invariant: "English  translation"
"en": "English  translation"
"de": ""

(the user set the translation to empty in the translation dialog in Admin UI without using the delete Button. So there is a translation in database, but it is empty)

If I get the translation for "de", I get the invariant translation (as fallback) instead of my expectation of "".

My suspection is that this behavior is controlled by a string.IsNullOrEmpty check in EPiServerGetTranslation.Execute()
(I would expect that fallback will be fetched only if a particular resource does not exist at all)

Issue can occur for instance when a developer creates a new resource with a beautiful text, then the resource editor thinks nothing should be displayed there at all and clears all translations. Invariant will be left over with my current settings, it is also not visible in AdminUI.
We also need fallback to invariant as not always all languages are translated (but in these cases there are null instead of "").

Thanks in advance!

**Comment by valdisiljuconoks** [comment]
v6 will have a bit redesigned fallback component to better match .NET Core provider logic and Episerver will be "plugged in" in the pipeline.

I can't tell ETA yet as v6 involves a lot of new features and bug fixes.

**Comment by nzsb** [comment]
Ok, thanks for the feedback!
