### ISSUE TITLE
Creating and deleting resources

### ISSUE THREAD

**Issue by monkeydtrochez** [valdisiljuconoks/localization-provider-epi#55]
Hi,

I have just installed this plugin and it seems pretty smooth! However i have a question regarding the possibility of creating and deleting resources from the admin ui.

I can see the create new resource button from the admin ui, however nothing seems to happend when i click on it. And i am logged in as a user with Administrator right, im not sure if i am missing something here with the configuration.
![image](https://user-images.githubusercontent.com/27406836/70808115-4a41b280-1dbf-11ea-895e-12f0f3429fba.png)

I am also wondering about deleting resources that is missing from code, is this possible somehow?

Thanks in advance! :) 

/Daniel

**Comment by valdisiljuconoks** [comment]
Thanks for the feedback. It should be all you need. No special configuration required to get this working. Will investigate

**Comment by monkeydtrochez** [comment]
Hi Valdis,

Thank you for your answer. I noticed that i had disabled the table view in my init module and it appears to be in the table view this is possible, so problem solved :) 

However while i have your attention i have another question. I read in the documentation that the cacheing did not suupport multilanguage sites, and i am using this tool in an multilanugage site. So i was wondering if there migt be another way to handle caching in this case? 
I was thinking of maybe building my own cache layer but i would need a way to disable the cache when updates to the localization resources happend from admin. Is there perhaps any update/save events that on could hook on to?

**Comment by valdisiljuconoks** [comment]
Hi,

Can you link to documentation? I'm just wondering. Regarding events - there are cache events coming from built-in CacheManager. But there are not events around create/update/delete. Just no one asked about those ;)

**Comment by monkeydtrochez** [comment]
https://blog.tech-fellow.net/2016/04/22/db-localization-provider-part-2-configuration-and-extensions/

Scroll down to the part about **UseCachedModelMetadataProviders** :)

**Comment by valdisiljuconoks** [comment]
Oh that one. Try it with cached settings as see if that works. Blog post is old enough

**Comment by monkeydtrochez** [comment]
Oh okej great! i will try that one :)
