### ISSUE TITLE
Help text translation disappeared

### ISSUE THREAD

**Issue by bsubasic** [valdisiljuconoks/localization-provider-epi#6]
Epi ver. 11.10.5.0
DbLocalizationProvider.EpiServer 5.0.0.0

After upgrading from 4.3.5.0 to the latest version, I noticed on some pages that **help text is not translated**/applied in the admin UI for the properties. Other translations work.

Translation screen:
![article_page_translation](https://user-images.githubusercontent.com/15268114/49729024-98841900-fc74-11e8-98e4-46fc9dd31250.jpg)

Code:
```
[ResourceKey("name", Value = "Article Page")]
    [ResourceKey("description", Value = "The article page used as a news article or as a general content page.")]
    [LocalizedResource(KeyPrefix = "/contenttypes/articlepage/", Inherited = false)]
    public class ArticlePageLocalization: IArticlePage
    {
        [ResourceKey("properties/heroimage/caption", Value = "Hero Image")]
        [ResourceKey("properties/heroimage/help", Value = "Set optional hero image.")]
        public Url HeroImage { get; set; }

        [ResourceKey("properties/title/caption", Value = "Title")]
        [ResourceKey("properties/title/help", Value = "Set article page title, if nothing is set page name will be used")]
        public string Title { get; set; }
        ... (omitted a rest of code)
```
I'm aware that Epi caches things a lot, I tried to restart app pool/website, but it didn't help.

What could be the problem?

Thanks

**Comment by valdisiljuconoks** [comment]
hi,

could it be an issue that Episerver has changed XPath conventions for these properties? Can you try to add the same keys to Xml language files and see if that solves the issue?

**Comment by bsubasic** [comment]
Thanks for the suggestion, I was having two page types with the same name "Article Page" but in different namespaces. So EpiServer created another with the name "Article Page(1)" because it needs to be unique, by default. But display name was the same "Article Page", so I didn't notice. I have renamed one of the page types and now it's OK 👍✔
