### ISSUE TITLE
Problems with cache

### ISSUE THREAD

**Issue by mkqvist** [valdisiljuconoks/localization-provider-epi#60]
Hi,

When managing items via the Episerver Localization UI we experience some trouble with the cache. We tried hooking up to the CacheManager-events and it seems that the only event that is triggered is CacheManager.OnRemove. (Only during initialization the CacheManager.OnInsert event is triggered).

Maybe we are missing something?

BR,
//Mikael

**Comment by valdisiljuconoks** [comment]
What trouble you have? Are you trying to catch when item has been added?

**Comment by mkqvist** [comment]
Hi Valdis,

Thanks for your quick reply.

We are using your LocalizationProvider as input in a SelectionFactory. When editors adds new items via the Epi-interface, the changes are not reflected in the dropdown generated from the SelectionFactory.

I tried to hook up to the OnInsert and OnRemove events:

ConfigurationContext.Setup(x =>
{
        x.DefaultResourceCulture = new CultureInfo("en");
        x.EnableLocalization = () => true;
        x.ModelMetadataProviders.UseCachedProviders = true;
        x.CacheManager.OnInsert += CacheManager_OnInsert;
        x.CacheManager.OnRemove += CacheManager_OnRemove;
});

The OnInsert-event are called during site initialization but when individual items are added or removed the OnRemove event is called.

Any ideas?

BR,
//Mikael

**Comment by valdisiljuconoks** [comment]
Hi,

Now I got your usage. OnInsert not being called sounds like a bug (but actually never thought anyone would be interested in that event).

But in your case - I think relying on cache events to produce selector factory source might not be quite reliable idea. I'm referring to case when cache expires and and new item is being added to the cache. You might end up with multiple entries in drop-down.

What about exposing specifically OnNewResourceCreated event? That would allow you to distinguish between cache invalidation and someone created new resource via UI?

**Comment by valdisiljuconoks** [comment]
Hei,

This is going to be possible in v6 via `UiConfigurationContext.Events.OnNewResourceCreated`
