### ISSUE TITLE
Javascript error when adding new resource

### ISSUE THREAD

**Issue by MagnusTeghammer** [valdisiljuconoks/localization-provider-epi#65]
When i click on the save button on a new resource i get an javascript error and nothing more happens. I have tried to clear browser cache.

![image](https://user-images.githubusercontent.com/807364/76859973-8f5fff80-685a-11ea-9333-3a37e13a39b5.png)

![image](https://user-images.githubusercontent.com/807364/76860464-5d02d200-685b-11ea-9d8d-e68519eb5994.png)

I´m running with these packages:

```
<package id="DbLocalizationProvider.AdminUI.EPiServer" version="6.0.1" targetFramework="net48" />
<package id="DbLocalizationProvider.EPiServer" version="6.0.1" targetFramework="net48" />
<package id="DbLocalizationProvider.MigrationTool" version="6.0.1" targetFramework="net48" />
<package id="LocalizationProvider" version="6.0.1" targetFramework="net48" />
<package id="LocalizationProvider.Abstractions" version="6.0.1" targetFramework="net48" />
<package id="LocalizationProvider.AspNet" version="6.0.1" targetFramework="net48" />
<package id="LocalizationProvider.Storage.SqlServer" version="6.0.1" targetFramework="net48" />
```

**Comment by valdisiljuconoks** [comment]
hi, blah I'm genius :)

do you see invariant culture column?

**Comment by MagnusTeghammer** [comment]
Hi,

It happens sometimes :)

This is what i see:
![image](https://user-images.githubusercontent.com/807364/76861518-01d1df00-685d-11ea-925f-bf58f42263b6.png)

**Comment by valdisiljuconoks** [comment]
yes, try please workaround to enable invariant culture column via `UiConfigurationContext`

**Comment by MagnusTeghammer** [comment]
Then it worked!

**Comment by valdisiljuconoks** [comment]
will fix in next patch. sorry for trouble

**Comment by valdisiljuconoks** [comment]
Look for v6.0.2

**Comment by MagnusTeghammer** [comment]
Thank you!

I see the new version for some of the packages but not for episerver.
I installed all of those but still the same error.

I these packages:
<package id="LocalizationProvider" version="6.0.2" targetFramework="net48" />
<package id="LocalizationProvider.Abstractions" version="6.0.2" targetFramework="net48" />
<package id="LocalizationProvider.AspNet" version="6.0.2" targetFramework="net48" />
<package id="LocalizationProvider.Storage.SqlServer" version="6.0.2" targetFramework="net48" />

**Comment by valdisiljuconoks** [comment]
yeah, episerver ones are still in "transit"
