### ISSUE TITLE
Possible to change or override allowed characters in key

### ISSUE THREAD

**Issue by MagnusTeghammer** [valdisiljuconoks/localization-provider-epi#66]
Hi,

I was wondering if it could be possible to change or override allowed characters in key.
In earlier version it was possible to add following chars:
- Swedish characters (åäö)
- Comma ( , )
- Underscore ( _ )
- Dash ( - )

We have a lot of keys already and more is coming from 3:e party system with those characters.

**Comment by valdisiljuconoks** [comment]
Yeah, sounds like good idea to pull out extension point here. Thx

**Comment by MagnusTeghammer** [comment]
Any ETA for 6.1?

**Comment by valdisiljuconoks** [comment]
Soon ;) But honestly - yeah. Working on few other features that wanted to put in scope for release. Should be out in coming weeks.
