### ISSUE TITLE
LocalizationResourceTranslations.Language column in database case sensitive

### ISSUE THREAD

**Issue by MathiasAnderssonKnowit** [valdisiljuconoks/localization-provider-epi#74]
Hi,

When importing XML translations from a file through the migration tool, the json that is generated does not take into account that the file language ID is case **insensitive** but when imported to the database it's case **sensitive**. We noticed this issue when migration from a market (de-at). The XML file had id="de-at" and when migrated to the json this was reflected, however to make the database translations work the LocalizationResourceTranslations.Language column had to be "de-AT" to match the CultureInfo.Name property correctly.

It might be a good idea to make the Language column case **insensitive** when looking up translations via the database, or fix the migration tool to match the cultureInfo.Name property instead of only taking the ID from the XML file.

**Comment by valdisiljuconoks** [comment]
eh, CI vs CS ;) good catch
