### ISSUE TITLE
Migration script generates invalid structure & error message missing on import

### ISSUE THREAD

**Issue by MathiasAnderssonKnowit** [valdisiljuconoks/localization-provider-epi#75]
Hi,

When using the Migration tool v 6.1.0 we get an incorrect structure on the JSON. The two fields "isModified" and "isHidden" are not present (on every label object), which is required for the import through the EPiServer Admin UI to work. This would be a QOL fix, it's easy enough to add those fields by ourselves. 

When performing an import via EPiServer admin UI v 6.0.2 with the preview mode **on** - we do not get any visible validation errors.
We only get the validation error when **not** using the preview mode.

**Comment by MathiasAnderssonKnowit** [comment]
FYI, here are two JSON examples.

Generated by the tool:
`[
  {
    "resourceKey": "/demo/testLabel",
    "modificationDate": "2020-06-12T10:37:38.1876134Z",
    "author": "migration-tool",
    "translations": [
      {
        "language": "en",
        "value": "Test label!"
      }
    ]
  }
]`

Manually fixed:
`[
  {
    "resourceKey": "/demo/testLabel",
    "modificationDate": "2020-06-12T10:37:38.1876134Z",
    "author": "migration-tool",
    "isModified": false,
    "isHidden": false,
    "translations": [
      {
        "language": "en",
        "value": "Test label!"
      }
    ]
  }
]`

**Comment by valdisiljuconoks** [comment]
looks like somebody pushed out release too early.. :)

**Comment by MathiasAnderssonKnowit** [comment]
> looks like somebody pushed out release too early.. :)

Could happen to anyone! Really enjoy the plugin otherwise and it's great when you get over these few bumps. :)

**Comment by valdisiljuconoks** [comment]
just hold on ;)
