### ISSUE TITLE
Issue when installing on EPi Foundation

### ISSUE THREAD

**Issue by sidu1987** [valdisiljuconoks/localization-provider-epi#76]
Hi Valdis,

I am working on EPi Foundation latest version (Master branch). I have an issue that upon installing the DbLocalizationProvider.EPiServer and DbLocalizationProvider.AdminUI.EPiServer nuget packages I get a 500 error.

https://www.screencast.com/t/Qcq7inUDq

I have also attached the packages config file in a txt format in case you want to have a look

[packages.txt](https://github.com/valdisiljuconoks/localization-provider-epi/files/5100531/packages.txt)

I dont see any errors on the logs and on the event viewer as well. Any help/advice on this is highly appreciated :)

**Comment by valdisiljuconoks** [comment]
Weirdo indeed. Do you have any setup code to configure provider? What about turning off custom errors?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sidu1987** [comment]
Hey Valdis,

Nope no customizations at all. I just cloned the Foundation master branch
and added the nuget. Turning off the custom errors doesn't seem to work
too, I did try that as well.

Regards,
Siddharth

**Comment by valdisiljuconoks** [comment]
You have to specify which storage provider to use. there is additional package that you can install to use a SQL server for the storage. and by doing that you have to have an initialization module where you specify a connection string to use to connect to the SQL Server. I think what you are experiencing now is an exception on the provider startup worth claims that it can't find any storage providers. maybe it should be in an exception but then it would be even harder maybe to figure it out that you are missing a setup code.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
