### ISSUE TITLE
Failed to load \bin\x86\SNI.dll

### ISSUE THREAD

**Issue by khurramkhang** [valdisiljuconoks/localization-provider-epi#77]
FYI only, You can close the issue after reading
After Upgrade from 5.7.2. to 6.2.0

Most of the developer was getting an issue
Failed to load ...l\bin\x86\SNI.dll

I upgraded Microsoft.Data.SqlClient 1.1.0 to 2.0.1.

That fixed the issue. :)

**Comment by valdisiljuconoks** [comment]
I can bump up to 2.x in provider 7.x version. But usually we saw this issue when sni.dll is not actually deployed to target server (due to weird packaging logic that copies files to output dir after packaging script has ran).

Does any of other projects pull in 2.x data client library?

**Comment by khurramkhang** [comment]
Nope, there is no other project within our solution, having reliance on 2.x
/K

**Comment by valdisiljuconoks** [comment]
Does sni.dll exist in output directory?

Is app pool set to 32bit?


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by khurramkhang** [comment]
For a developer when it worked dll was in x86 folder, but in case of
cleaning solution and removing bin folder, the Package wasn't restoring. i
i think all run app in iis express
/K

**Comment by valdisiljuconoks** [comment]
As said - we also noticed some weird behaviour of that package when it comes to copying files. Ok - will bump to 2.x version then.


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by khurramkhang** [comment]
Thanks :)

**Comment by khurramkhang** [comment]
We are having another weird issue during automatic release (Azure Cloud web Aps)
Error Code: ERROR_FILE_IN_USE More Information: Web Deploy cannot modify the file 'Microsoft.Data.SqlClient.SNI.x64.

Have to Stop WebApp/Release/Start App

**Comment by valdisiljuconoks** [comment]
Welcome to SqlClient package world ;)


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by valdisiljuconoks** [comment]
![image](https://user-images.githubusercontent.com/1767179/97329405-ab5f6100-187f-11eb-8f05-c3b8365f9f95.png)
