### ISSUE TITLE
Updated from 6.0.2 to 6.2.0, exception: Field not found: 'DbLocalizationProvider.Cache.BaseCacheManager.KnownResourceKeys'.

### ISSUE THREAD

**Issue by VaclavRoncka** [valdisiljuconoks/localization-provider-epi#79]
All of theese were 6.0.2 and it worked fine until I updated to 6.2.0
  package id="DbLocalizationProvider.AdminUI.EPiServer" version="6.2.0" targetFramework="net472"
  package id="DbLocalizationProvider.EPiServer" version="6.2.0" targetFramework="net472"
  package id="LocalizationProvider" version="6.2.0" targetFramework="net472"
  package id="LocalizationProvider.Abstractions" version="6.2.0" targetFramework="net472"
  package id="LocalizationProvider.AspNet" version="6.2.0" targetFramework="net472"

[MissingFieldException: Field not found: 'DbLocalizationProvider.Cache.BaseCacheManager.KnownResourceKeys'.]
   DbLocalizationProvider.Storage.SqlServer.GetTranslationHandler.Execute(Query query) +0
   DbLocalizationProvider.Queries.Internal.QueryHandlerWrapper`2.Execute(IQuery`1 message) +72
   DbLocalizationProvider.IQueryExtensions.Execute(IQuery`1 query) +74
   DbLocalizationProvider.LocalizationProvider.GetStringByCulture(String resourceKey, CultureInfo culture, Object[] formatArguments) +83
   DbLocalizationProvider.LocalizationProvider.GetStringByCulture(Expression`1 resource, CultureInfo culture, Object[] formatArguments) +35
   DbLocalizationProvider.HtmlHelperExtensions.Translate(HtmlHelper helper, Expression`1 model, Object[] formatArguments) +68
   ASP.episerver_dblocalizationprovider_adminui_episerver_views_localizationresources_index_aspx.__Render__control3(HtmlTextWriter __w, Control parameterContainer) in C:\Git\Neles\Neles.Web\EPiServer\DbLocalizationProvider.AdminUI.EPiServer\Views\LocalizationResources\Index.aspx:19
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +103
   System.Web.UI.Control.RenderChildren(HtmlTextWriter writer) +9
   System.Web.UI.HtmlControls.HtmlTitle.Render(HtmlTextWriter writer) +61
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +129
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +287
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +27
   ASP.episerver_dblocalizationprovider_adminui_episerver_views_localizationresources_index_aspx.__Render__control2(HtmlTextWriter __w, Control parameterContainer) in C:\Git\Neles\Neles.Web\EPiServer\DbLocalizationProvider.AdminUI.EPiServer\Views\LocalizationResources\Index.aspx:0
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +103
   System.Web.UI.HtmlControls.HtmlHead.RenderChildren(HtmlTextWriter writer) +21
   System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) +32
   System.Web.UI.Adapters.ControlAdapter.Render(HtmlTextWriter writer) +17
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +81
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +287
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +27
   ASP.episerver_dblocalizationprovider_adminui_episerver_views_localizationresources_index_aspx.__Render__control1(HtmlTextWriter __w, Control parameterContainer) in C:\Git\Neles\Neles.Web\EPiServer\DbLocalizationProvider.AdminUI.EPiServer\Views\LocalizationResources\Index.aspx:0
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +103
   System.Web.UI.Control.RenderChildren(HtmlTextWriter writer) +9
   System.Web.Mvc.ViewPage.Render(HtmlTextWriter writer) +63
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +129
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +287
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +27
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +5635

**Comment by valdisiljuconoks** [comment]
Yeah, it's my fault. Sorry for that. Can you check that you have all libs setup to latest version?

**Comment by valdisiljuconoks** [comment]
I'll fix this in next minor version

**Comment by VaclavRoncka** [comment]
Thank you for your quick response 👍 
What do you mean by "All" ? 
From LocalizationProvider / DbLocalizationProvider I have the latest..
If you are asking for Episerver version? Yes I updated all to the latest also.
When do you expect to release next minor version?
Thank you.

**Comment by valdisiljuconoks** [comment]
Which version you have for SqlServer package? 

I think I'll need to push out earlier as more reports are coming in for the version incompatibility..

**Comment by VaclavRoncka** [comment]
I already updated everything (Epi, microsoft etc... ) to the latest version and it is working fine ...
Anyway i will return to one commit and put here the lpackages.config to show you when it is not working.

**Comment by VaclavRoncka** [comment]
This is my current (WORKIG FINE) setup:
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Alloy.HideTabs" version="1.0.1" targetFramework="net472" />
  <package id="Castle.Core" version="4.4.1" targetFramework="net472" />
  <package id="Castle.Windsor" version="4.1.1" targetFramework="net472" />
  <package id="DbLocalizationProvider.AdminUI.EPiServer" version="6.2.0" targetFramework="net472" />
  <package id="DbLocalizationProvider.EPiServer" version="6.2.0" targetFramework="net472" />
  <package id="EntityFramework" version="6.4.4" targetFramework="net472" />
  <package id="EPiServer.Azure" version="10.0.1" targetFramework="net472" />
  <package id="EPiServer.CMS" version="11.19.0" targetFramework="net472" />
  <package id="EPiServer.CMS.AspNet" version="11.19.0" targetFramework="net472" />
  <package id="EPiServer.CMS.Core" version="11.19.0" targetFramework="net472" />
  <package id="EPiServer.CMS.TinyMce" version="2.13.0" targetFramework="net472" />
  <package id="EPiServer.CMS.UI" version="11.30.0" targetFramework="net472" />
  <package id="EPiServer.CMS.UI.Core" version="11.30.0" targetFramework="net472" />
  <package id="EPiServer.ConnectForSharePoint" version="2.3.4" targetFramework="net472" />
  <package id="EPiServer.Find" version="13.2.9" targetFramework="net472" />
  <package id="EPiServer.Find.Cms" version="13.2.9" targetFramework="net472" />
  <package id="EPiServer.Find.Framework" version="13.2.9" targetFramework="net472" />
  <package id="EPiServer.Framework" version="11.19.0" targetFramework="net472" />
  <package id="EPiServer.Framework.AspNet" version="11.19.0" targetFramework="net472" />
  <package id="EPiServer.Labs.BlockEnhancements" version="0.9.5" targetFramework="net472" />
  <package id="EPiServer.Labs.LanguageManager" version="4.0.1" targetFramework="net472" />
  <package id="EPiServer.Logging.Log4Net" version="2.2.2" targetFramework="net472" />
  <package id="EPiServer.Packaging" version="3.4.0" targetFramework="net472" />
  <package id="EPiServer.ServiceLocation.StructureMap" version="2.0.3" targetFramework="net472" />
  <package id="EPiServer.Telemetry.UI" version="1.0.9" targetFramework="net472" />
  <package id="EPiServer.Telemetry.UI.Core" version="1.0.9" targetFramework="net472" />
  <package id="Geta.EpiCategories" version="1.2.11" targetFramework="net472" />
  <package id="Geta.EpiCategories.Find" version="1.2.11" targetFramework="net472" />
  <package id="HtmlAgilityPack" version="1.11.24" targetFramework="net472" />
  <package id="Ical.Net" version="4.1.11" targetFramework="net472" />
  <package id="ImageProcessor" version="2.9.1" targetFramework="net472" />
  <package id="ImageProcessor.Plugins.WebP" version="1.3.0" targetFramework="net472" />
  <package id="ImageProcessor.Web" version="4.12.1" targetFramework="net472" />
  <package id="ImageProcessor.Web.Config" version="2.6.0" targetFramework="net472" />
  <package id="ImageProcessor.Web.Episerver" version="5.6.3.41017" targetFramework="net472" />
  <package id="LocalizationProvider" version="6.2.2" targetFramework="net472" />
  <package id="LocalizationProvider.Abstractions" version="6.2.2" targetFramework="net472" />
  <package id="LocalizationProvider.AspNet" version="6.2.0" targetFramework="net472" />
  <package id="LocalizationProvider.Storage.SqlServer" version="6.2.2" targetFramework="net472" />
  <package id="log4net" version="2.0.11" targetFramework="net472" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.Providers.Core" version="2.0.0" targetFramework="net472" />
  <package id="Microsoft.AspNet.Razor" version="3.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.7" targetFramework="net472" />
  <package id="Microsoft.Azure.KeyVault.Core" version="3.0.5" targetFramework="net472" />
  <package id="Microsoft.Azure.Services.AppAuthentication" version="1.6.0" targetFramework="net472" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="3.6.0" targetFramework="net472" />
  <package id="Microsoft.Data.SqlClient" version="2.0.1" targetFramework="net472" />
  <package id="Microsoft.Data.SqlClient.SNI" version="2.1.0" targetFramework="net472" />
  <package id="Microsoft.Identity.Client" version="4.19.0" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="5.2.8" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.JsonWebTokens" version="6.7.1" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.Logging" version="6.7.1" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.Protocols" version="6.7.1" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="6.7.1" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.Tokens" version="6.7.1" targetFramework="net472" />
  <package id="Microsoft.IO.RecyclableMemoryStream" version="1.3.5" targetFramework="net472" />
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.22" targetFramework="net472" />
  <package id="Microsoft.Rest.ClientRuntime.Azure" version="3.3.19" targetFramework="net472" />
  <package id="Microsoft.SharePoint.Client.Runtime.dll" version="15.0.4859.1000" targetFramework="net472" />
  <package id="Microsoft.Tpl.Dataflow" version="4.5.24" targetFramework="net472" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net472" />
  <package id="Microsoft.Web.Xdt" version="3.1.0" targetFramework="net472" />
  <package id="Newtonsoft.Json" version="12.0.3" targetFramework="net472" />
  <package id="NodaTime" version="3.0.0" targetFramework="net472" />
  <package id="NuGet.Core" version="2.7.2" targetFramework="net472" />
  <package id="Owin" version="1.0" targetFramework="net472" />
  <package id="RestSharp" version="106.11.7" targetFramework="net472" />
  <package id="StructureMap" version="4.7.1" targetFramework="net472" />
  <package id="structuremap.web" version="4.0.0.315" targetFramework="net472" />
  <package id="System.ComponentModel.Annotations" version="4.7.0" targetFramework="net472" />
  <package id="System.Data.Common" version="4.3.0" targetFramework="net472" />
  <package id="System.Data.SqlClient" version="4.8.2" targetFramework="net472" />
  <package id="System.IdentityModel.Tokens.Jwt" version="6.7.1" targetFramework="net472" />
  <package id="System.IO" version="4.3.0" targetFramework="net472" />
  <package id="System.Net.Http" version="4.3.4" targetFramework="net472" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net472" />
  <package id="System.Reflection.Emit" version="4.7.0" targetFramework="net472" />
  <package id="System.Reflection.Emit.Lightweight" version="4.7.0" targetFramework="net472" />
  <package id="System.Reflection.TypeExtensions" version="4.7.0" targetFramework="net472" />
  <package id="System.Runtime" version="4.3.1" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.7.1" targetFramework="net472" />
  <package id="System.Runtime.Serialization.Primitives" version="4.3.0" targetFramework="net472" />
  <package id="System.Security.AccessControl" version="4.7.0" targetFramework="net472" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net472" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net472" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net472" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="net472" />
  <package id="System.Security.Cryptography.Xml" version="4.7.0" targetFramework="net472" />
  <package id="System.Security.Permissions" version="4.7.0" targetFramework="net472" />
  <package id="System.Security.Principal.Windows" version="4.7.0" targetFramework="net472" />
  <package id="System.Threading.AccessControl" version="4.7.0" targetFramework="net472" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net472" />
  <package id="Verndale.RedirectManager" version="1.0.0.6" targetFramework="net472" />
  <package id="WindowsAzure.ServiceBus" version="6.0.3" targetFramework="net472" />
  <package id="WindowsAzure.Storage" version="9.3.3" targetFramework="net472" />
</packages>

**Comment by VaclavRoncka** [comment]
This is NON WORKING version:
package id="Alloy.HideTabs" version="1.0.1" targetFramework="net472" />
package id="Castle.Core" version="4.4.0" targetFramework="net472" />
package id="Castle.Windsor" version="4.1.1" targetFramework="net472" />
package id="DbLocalizationProvider.AdminUI.EPiServer" version="6.2.0" targetFramework="net472" />
package id="DbLocalizationProvider.EPiServer" version="6.2.0" targetFramework="net472" />
package id="EntityFramework" version="6.4.0" targetFramework="net472" />
package id="EPiServer.Azure" version="10.0.1" targetFramework="net472" />
package id="EPiServer.CMS" version="11.19.0" targetFramework="net472" />
package id="EPiServer.CMS.AspNet" version="11.19.0" targetFramework="net472" />
package id="EPiServer.CMS.Core" version="11.19.0" targetFramework="net472" />
package id="EPiServer.CMS.TinyMce" version="2.13.0" targetFramework="net472" />
package id="EPiServer.CMS.UI" version="11.30.0" targetFramework="net472" />
package id="EPiServer.CMS.UI.Core" version="11.30.0" targetFramework="net472" />
package id="EPiServer.ConnectForSharePoint" version="2.3.4" targetFramework="net472" />
package id="EPiServer.Find" version="13.2.9" targetFramework="net472" />
package id="EPiServer.Find.Cms" version="13.2.9" targetFramework="net472" />
package id="EPiServer.Find.Framework" version="13.2.9" targetFramework="net472" />
package id="EPiServer.Framework" version="11.19.0" targetFramework="net472" />
package id="EPiServer.Framework.AspNet" version="11.19.0" targetFramework="net472" />
package id="EPiServer.Labs.LanguageManager" version="4.0.1" targetFramework="net472" />
package id="EPiServer.Logging.Log4Net" version="2.2.2" targetFramework="net472" />
package id="EPiServer.Packaging" version="3.4.0" targetFramework="net472" />
package id="EPiServer.ServiceLocation.StructureMap" version="2.0.3" targetFramework="net472" />
package id="Geta.EpiCategories" version="1.2.11" targetFramework="net472" />
package id="Geta.EpiCategories.Find" version="1.2.11" targetFramework="net472" />
package id="HtmlAgilityPack" version="1.11.21" targetFramework="net472" />
package id="Ical.Net" version="4.1.11" targetFramework="net472" />
package id="ImageProcessor" version="2.9.0" targetFramework="net472" />
package id="ImageProcessor.Plugins.WebP" version="1.3.0" targetFramework="net472" />
package id="ImageProcessor.Web" version="4.12.0" targetFramework="net472" />
package id="ImageProcessor.Web.Config" version="2.6.0" targetFramework="net472" />
package id="ImageProcessor.Web.Episerver" version="5.6.3.41017" targetFramework="net472" />
package id="LocalizationProvider" version="6.2.0" targetFramework="net472" />
package id="LocalizationProvider.Abstractions" version="6.2.0" targetFramework="net472" />
package id="LocalizationProvider.AspNet" version="6.2.0" targetFramework="net472" />
package id="LocalizationProvider.Storage.SqlServer" version="6.2.0" targetFramework="net472" />
package id="log4net" version="2.0.8" targetFramework="net472" />
package id="Microsoft.AspNet.Mvc" version="5.2.7" targetFramework="net472" />
package id="Microsoft.AspNet.Providers.Core" version="2.0.0" targetFramework="net472" />
package id="Microsoft.AspNet.Razor" version="3.2.7" targetFramework="net472" />
package id="Microsoft.AspNet.WebApi" version="5.2.7" targetFramework="net472" />
package id="Microsoft.AspNet.WebApi.Client" version="5.2.7" targetFramework="net472" />
package id="Microsoft.AspNet.WebApi.Core" version="5.2.7" targetFramework="net472" />
package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.7" targetFramework="net472" />
package id="Microsoft.AspNet.WebPages" version="3.2.7" targetFramework="net472" />
package id="Microsoft.Azure.KeyVault.Core" version="3.0.5" targetFramework="net472" />
package id="Microsoft.Azure.Services.AppAuthentication" version="1.4.0" targetFramework="net472" />
package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="2.0.1" targetFramework="net472" />
package id="Microsoft.Data.SqlClient" version="1.1.0" targetFramework="net472" />
package id="Microsoft.Data.SqlClient.SNI" version="1.1.0" targetFramework="net472" />
package id="Microsoft.Identity.Client" version="3.0.8" targetFramework="net472" />
package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="5.2.7" targetFramework="net472" />
package id="Microsoft.IdentityModel.JsonWebTokens" version="5.6.0" targetFramework="net472" />
package id="Microsoft.IdentityModel.Logging" version="5.6.0" targetFramework="net472" />
package id="Microsoft.IdentityModel.Protocols" version="5.5.0" targetFramework="net472" />
package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="5.5.0" targetFramework="net472" />
package id="Microsoft.IdentityModel.Tokens" version="5.6.0" targetFramework="net472" />
package id="Microsoft.IO.RecyclableMemoryStream" version="1.2.2" targetFramework="net472" />
package id="Microsoft.Rest.ClientRuntime" version="2.3.21" targetFramework="net472" />
package id="Microsoft.Rest.ClientRuntime.Azure" version="3.3.19" targetFramework="net472" />
package id="Microsoft.SharePoint.Client.Runtime.dll" version="15.0.4859.1000" targetFramework="net472" />
package id="Microsoft.Tpl.Dataflow" version="4.5.24" targetFramework="net472" />
package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net472" />
package id="Microsoft.Web.Xdt" version="3.0.0" targetFramework="net472" />
package id="Newtonsoft.Json" version="11.0.2" targetFramework="net472" />
package id="NodaTime" version="2.0.2" targetFramework="net472" />
package id="NuGet.Core" version="2.7.2" targetFramework="net472" />
package id="Owin" version="1.0" targetFramework="net472" />
package id="RestSharp" version="106.10.1" targetFramework="net472" />
package id="StructureMap" version="4.7.1" targetFramework="net472" />
package id="structuremap.web" version="4.0.0.315" targetFramework="net472" />
package id="System.ComponentModel.Annotations" version="4.7.0" targetFramework="net472" />
package id="System.Data.Common" version="4.3.0" targetFramework="net472" />
package id="System.Data.SqlClient" version="4.8.1" targetFramework="net472" />
package id="System.IdentityModel.Tokens.Jwt" version="5.6.0" targetFramework="net472" />
package id="System.IO" version="4.3.0" targetFramework="net472" />
package id="System.Net.Http" version="4.3.4" targetFramework="net472" />
package id="System.Reflection" version="4.1.0" targetFramework="net472" />
package id="System.Reflection.Emit" version="4.7.0" targetFramework="net472" />
package id="System.Reflection.Emit.Lightweight" version="4.7.0" targetFramework="net472" />
package id="System.Reflection.TypeExtensions" version="4.1.0" targetFramework="net472" />
package id="System.Runtime" version="4.3.1" targetFramework="net472" />
package id="System.Runtime.Serialization.Primitives" version="4.3.0" targetFramework="net472" />
package id="System.Security.AccessControl" version="4.7.0" targetFramework="net472" />
package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net472" />
package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net472" />
package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net472" />
package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="net472" />
package id="System.Security.Cryptography.Xml" version="4.7.0" targetFramework="net472" />
package id="System.Security.Permissions" version="4.7.0" targetFramework="net472" />
package id="System.Security.Principal.Windows" version="4.7.0" targetFramework="net472" />
package id="System.Threading.AccessControl" version="4.7.0" targetFramework="net472" />
package id="System.ValueTuple" version="4.5.0" targetFramework="net472" />
package id="Verndale.RedirectManager" version="1.0.0.5" targetFramework="net472" />
package id="WindowsAzure.ServiceBus" version="6.0.1" targetFramework="net472" />
package id="WindowsAzure.Storage" version="9.3.3" targetFramework="net472" />
