### ISSUE TITLE
Removing a localized label

### ISSUE THREAD

**Issue by pamiddleton** [valdisiljuconoks/localization-provider-epi#8]
Hi, 

The localization provider works really well, but we have noticed something when using it to translate labels across multiple languages. 
If you provide a localized string in a particular language, then decide you no longer want to localize, there is no way to revert the localized label in that particular language. 
If you simply provide a null string, the translation of the label is saved in the DB, and the entry still remains, meaning the empty label is displayed on the site. 
I'd have expected the tool to use the fallback language if the translation for a language was null. 

If there any way to get this behavior to work as I would like?

Thanks very much,
Paul

**Comment by valdisiljuconoks** [comment]
>  "one workaround (until I will find solution) would be to set the same translation as fallback language translation."

what I mean here is - if for instance, you have English translation = "Label (EN)", and en-CA = "Label (CA)". If you want to remove translation and fallback to English - this could be done just by setting en-CA to "Label (EN)". Silly, but might work.

**Comment by valdisiljuconoks** [comment]
also, I'm not sure anymore whether that version had fallback fix, but there has been some experiments around fallback language lately. check out this post (https://blog.tech-fellow.net/2018/09/29/double-language-fallback-behavior-in-episerver/) - maybe can give some hints. I'll experiment further with fallbacks.

can you paste your fallback setup from web.config?

**Comment by pamiddleton** [comment]
I see what you mean - yes this would work but I think the advantage of reverting/removing the localized label would be that in future all updates at EN, would cascade down - I think this is the reason why it was raised to me initially - if an editor provided a value at a specific language then decided they just wanted to take _whatever_ was at EN.

So our current config is as follows:

<localization fallbackBehavior="Echo, MissingMessage, FallbackCulture" fallbackCulture="en">
            <providers>
                <add name="db" type="DbLocalizationProvider.EPiServer.DatabaseLocalizationProvider, DbLocalizationProvider.EPiServer" />
            </providers>
        </localization>

I will take a look at your blog post thanks.

**Comment by valdisiljuconoks** [comment]
also, looking at config, IMHO you need to change order of fallback behavior attribute to get fallback kicked in..

**Comment by pamiddleton** [comment]
Reordering didn't seem to have any affect unfortunately. 
If you can think of any way of allowing to fallback if a label is empty, let me know, it would be much appreciated! 

Thanks

**Comment by valdisiljuconoks** [comment]
yes, missing remove translation option in UI. currently there is no easy way around this unless you delete translation from db

**Comment by valdisiljuconoks** [comment]
check feed for 5.3 version

**Comment by valdisiljuconoks** [comment]
btw, delete command is available only for resources that are manually edited. for synced resources - remove translation is not available as translation from code will be overwritten on next sync anyways..
