### ISSUE TITLE
How to use GetTranslations with Prefix?

### ISSUE THREAD

**Issue by wojciechGabelBright** [valdisiljuconoks/localization-provider-epi#85]
Hi!
When using `[LocalizedResource(KeyPrefix = "Foo")]` how can I reference this prefix in the Html.GetTranslations method? This method input is a Type, and this is just a string. How to use this? We need that because the Localized Resource is nested with multiple levels of classes and on top of that there is a lengthy Namespace, so now editor need to add a mile of key name just to add a label to the translations table in the admin view. Also, when using this `prefix` the classes are listed in the admin view correctly, with the short `Foo` prefix, but we cannot reference that in the code, so we get no translations.

```
namespace Some.NameSpace.That.Is.Too.Long.To.Type.For.A.Editor
{
   [LocalizedResource(KeyPrefix = "Foo")]
  class Translations
  {
     //multiple nested classes here...
  }
}

view:
//...
@Html.GetTranslations(typeof(Some.NameSpace.That.Is.Too.Long.To.Type.For.A.Editor.Translations));

**Comment by valdisiljuconoks** [comment]
Hi, when you are using prefix, you have to use stringly typed APIs unfortunately. So it would be `GetString("...")`
