### ISSUE TITLE
Error when upgrading from 6.02

### ISSUE THREAD

**Issue by MathiasAnderssonKnowit** [valdisiljuconoks/localization-provider-epi#86]
Hi,

When we're trying to update the plugin from 6.02 we get an error and I believe it's related to an updated table schema. 

The error we received was "Invalid column name 'ModificationDate'." and when I compare the table schemas from https://github.com/valdisiljuconoks/LocalizationProvider/blob/b42b2e6509899a644d6d90c91183a129beb590a0/src/DbLocalizationProvider.Storage.SqlServer/SchemaUpdater.cs and what we have I can see that we're missing the "ModificationDate" on the "LocalizationResourceTranslations" table. 

Is there a migration job missing for this?

Br,
Mathias

**Comment by valdisiljuconoks** [comment]
Hmm, 

this does not work on your db?

https://github.com/valdisiljuconoks/LocalizationProvider/blob/b42b2e6509899a644d6d90c91183a129beb590a0/src/DbLocalizationProvider.Storage.SqlServer/SchemaUpdater.cs#L129

**Comment by MathiasAnderssonKnowit** [comment]
Hi,

It did not unfortunately, we had to make our own migration for this. We also noticed errors when the index ix_UniqueTranslationForLanguage was created (this was created when updating the tool). We had some duplicate keys which caused a hard exception and we had to create a migration for this as well.

Br,
Mathias

**Comment by valdisiljuconoks** [comment]
That is strange. I've tested different migration paths to see how this will work. Which SQL version are you running? Chances of half migrated state somehow?

**Comment by MathiasAnderssonKnowit** [comment]
There was a chance of half migration, after I upgraded I was just met with a generic 500 error and in the event viewer I could see the error above.
I was running Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) when I got this error, however on another machine the migration worked by itself.

**Comment by valdisiljuconoks** [comment]
If you do have repro steps, please reopen
