### ISSUE TITLE
Possibility to add custom locking around initialization

### ISSUE THREAD

**Issue by nzsb** [valdisiljuconoks/localization-provider-epi#87]
Hi Valdis,

I am wondering if it is possible to add custom logic around the initialization, like locking. With the normal ASP.NET initialization it looks possible because we have the control when it happens synchronously, but the in the Episerver package the ConfigurationContext.Setup does not do the initialization itself (although the XML comment says so), but it happens as an Episerver post-initialization step registered with InitComplete, where we have no more control at all.
Background: with 12 servers it happens regularly, that DbLocalizationProvider tries to create new resources at the same time on different servers, when starting up at the same time (and we even plan to use DbLocalizationProvider with the same database in even more projects, it would go up to around 40 server instances). So I was thinking about to add locking around the initialization, to be sure. I know you added a unique constraint to avoid duplicate keys, but it would be safer to do proper locking, what do you think about an extension point before and after the initialization?

Thanks and Regards,
Zsolt

**Comment by valdisiljuconoks** [comment]
Hey,

I hear you :) This been hanging around for a while (actually all this crap in the world kicked me aside a bit). I'm now working on v7 version - which seems to be quite big with some major improvements and features.

Your particularly is - https://github.com/valdisiljuconoks/LocalizationProvider/issues/190

**Comment by valdisiljuconoks** [comment]
Btw, I assume that you might have some sort of cloud storage available? I'll add extension points, but I'm thinking about similar functionality that azure functions / webjobs are using for example - they acquire lock on azure storage blob (that is their semaphore).

**Comment by nzsb** [comment]
Cool, you are always one step ahead!
Funny thing is our monster is running on premises (it was a requirement from the customer) :-)
Therefore locking on blob or similar Azure stuff are not possible for us, but I don't see why adding more infrastructure to the lib, we already have a database to lock on, why not just use standard MSSQL sp_getapplock - sp_releaseapplock, it is also supported on Azure SQL?
I see you support pgsql now as well, I hope there is something like that as well, I am not sure.

**Comment by nzsb** [comment]
Do you have any update on this topic? For us it would be great if there would be an event before and after the initialization, where we can apply our own locking logic (as InitializationModule does only the configuration), would it be possible to implement such before the next major release?

**Comment by valdisiljuconoks** [comment]
It's been bizzare lately :)

Originally this feature was planned for the v7 (aligned with Optimizely v12 release).
Tracking issue - https://github.com/valdisiljuconoks/LocalizationProvider/issues/190

I'm not sure that simple event around initialization will solve the whole problem. It might be temp solution to check lock state yourself and prevent programmatically provider to initialize.

**Comment by nzsb** [comment]
Yes you are right, we would need an event where we it is possible to "hang" the initialization process, so it will not go further if code from the event is not yet returned. Then another event after the initialization process would release the lock. Of course it would only be a temp solution until a proper way is implemented in the engine itself.

**Comment by valdisiljuconoks** [comment]
hey,

what do you think?

```csharp
ConfigurationContext.Setup(_ =>
{
    _.SynchronizationCoordinator.BeforeSyncCallback = BeforeSyncCallback;
    _.SynchronizationCoordinator.OnSyncCompleted += OnSyncCompleted;
});
```

```
private void BeforeSyncCallback()
{
    Thread.Sleep(5000);
}

private void OnSyncCompleted()
{

}
```

**Comment by nzsb** [comment]
Looks perfect for us to implement the custom locking, thanks!
