### ISSUE TITLE
language fallback  problem with versions higher than 5.3.0 (episerver)

### ISSUE THREAD

**Issue by mhwlng** [valdisiljuconoks/localization-provider-epi#9]
Hello,
I use this library with episerver
If I use nuget packages > 5.3.0
Then I see in the admin UI only the 4 main languages that have resources:
![image](https://user-images.githubusercontent.com/1388886/53786371-d9aa6300-3f1b-11e9-8884-48ccb9df73e2.png)
so e.g. fallback from nl-BE to nl won't work anymore.

With 5.3.0 I see in the admin UI all languages that exist in Episerver:
![image](https://user-images.githubusercontent.com/1388886/53786388-e3cc6180-3f1b-11e9-9427-dfe75eb0daad.png)
now e.g. fallback from en-GB to en works fine

**Comment by valdisiljuconoks** [comment]
moved issue from core repo.

**Comment by valdisiljuconoks** [comment]
this is strange, as I cannot repro with 5.4 locally:

![image](https://user-images.githubusercontent.com/1767179/53786940-7de0d980-3f1d-11e9-9a6f-b19e4ab3559e.png)

do you have similar setup in epi?

**Comment by mhwlng** [comment]
yes it looks similar

![image](https://user-images.githubusercontent.com/1388886/53787110-06f81080-3f1e-11e9-962c-9060a75d4dc3.png)

resources are defined only for the main languages like :
        [TranslationForCulture("Naar de homepagina", "nl")]
        [TranslationForCulture("À la page d'accueil", "fr")]
        [TranslationForCulture("Zur Startseite", "de")]
        public static string ToHomepage => "To the homepage";

**Comment by valdisiljuconoks** [comment]
list of languages is taken from episerver available languages, can you repo with 5.4?

**Comment by mhwlng** [comment]
the first screenshot at the top is with 5.4
it only shows 4 languages that have resources
as soon as I change localizationprovider to 5.3.1 or higher, I see this

**Comment by valdisiljuconoks** [comment]
can you repro this in clean alloy?

**Comment by mhwlng** [comment]
yes. same problem (latest nuget versions of everything)
![image](https://user-images.githubusercontent.com/1388886/53804874-ed1ff300-3f48-11e9-88c8-af3806fbf82d.png)
![image](https://user-images.githubusercontent.com/1388886/53804883-f3ae6a80-3f48-11e9-837f-79b8468b58c2.png)

**Comment by valdisiljuconoks** [comment]
this is even more odd. have exactly the same setup.. no repro. is it possible for you to drop me a link to project repo?

**Comment by mhwlng** [comment]
I sent dropbox link to your email

**Comment by valdisiljuconoks** [comment]
ok, I got it. this might a bit misleading, but you don't need `LocalizationProvider.AspNet` package when running in Episerver. this is required *only* for "pure" Asp.Net Mvc apps. which means that you don't need also this fragment:

```csharp
app.UseDbLocalizationProvider(cfg =>
{
    cfg.DefaultResourceCulture = new CultureInfo("en");
    cfg.ModelMetadataProviders.EnableLegacyMode = () => true;
    cfg.Connection = "EPiServerDB";
});
```

instead, either you just rely on default settings that are set in Episerver init module, or customize it via following approach:

```csharp
[InitializableModule]
[ModuleDependency(typeof(InitializationModule))]
public class InitLocalization : IInitializableModule
{
    public void Initialize(InitializationEngine context)
    {
        ConfigurationContext.Setup(_ =>
                                   {
                                       _.ModelMetadataProviders.EnableLegacyMode = () => true;
                                       _.EnableInvariantCultureFallback = true;
                                       _.DefaultResourceCulture = CultureInfo.InvariantCulture;
                                   });

        UiConfigurationContext.Setup(_ =>
                                     {
                                         _.TreeViewExpandedByDefault = true;
                                         _.ShowInvariantCulture = true;
                                     });
    }

    public void Uninitialize(InitializationEngine context)
    {
    }
}
```

hope this will solve your issues

**Comment by mhwlng** [comment]
> You don't need LocalizationProvider.AspNet package when running in Episerver.

I see
Unable to uninstall 'LocalizationProvider.AspNet.5.3.0' because 'DbLocalizationProvider.AdminUI.EPiServer.5.3.0, 
DbLocalizationProvider.AdminUI.EPiServer.Xliff.5.3.0, 
DbLocalizationProvider.EPiServer.5.3.0, 
DbLocalizationProvider.EPiServer.JsResourceHandler.5.3.0' depend on it.

**Comment by valdisiljuconoks** [comment]
I'm lazy.. sorry - you don't need to *initialize* from aspnet package. run through epi module if you need to customize, or just leave it to defaults..

**Comment by mhwlng** [comment]
yes, now it works again.

Thank you very much for your help!

**Comment by mhwlng** [comment]
Hello,
sorry to reopen this

now my test resource have fromcode field = 0
and don't get updated anymore ?


```
SELECT [Id]
      ,[ResourceKey]
      ,[ModificationDate]
      ,[Author]
      ,[FromCode]
      ,[IsModified]
      ,[IsHidden]
  FROM [EPiServerDB_1848eeb6].[dbo].[LocalizationResources]
```

```
Id	ResourceKey	ModificationDate	Author	FromCode	IsModified	IsHidden
37	Alloy.Resources.FaqResources.WhatAreYouLookingFor	2019-03-08 10:33:59.290	type-scanner	0	0	0
38	Alloy.Resources.FaqResources.NoMatchingResults	2019-03-08 10:33:59.293	type-scanner	0	0	0
39	Alloy.Resources.FaqResources.MoreInformation	2019-03-08 10:33:59.293	type-scanner	0	0	0
40	Alloy.Resources.FaqResources.ViewAllQuestions	2019-03-08 10:33:59.293	type-scanner	0	0	0
41	Alloy.Resources.FaqResources.BackToTop	2019-03-08 10:33:59.297	type-scanner	0	0	0
```
