### ISSUE TITLE
Using MemoryLocalizationService with GetString(() => ...) lambda throws a KeyNotFoundException

### ISSUE THREAD

**Issue by andreas-valtech** [valdisiljuconoks/localization-provider-epi#97]
We are using `EPiServer.Framework.Localization.MemoryLocalizationService` in some tests and has found that it is not possible to use the `GetString(() => MyResource.SomeLabel)` extension method together.

In our test we setup the localizationService like this:

```
var localizationService = new MemoryLocalizationService();
localizationService.AddString(CultureInfo.CurrentUICulture, "MyResource.SomeLabel", "Some label");

```
Then later in the test we call

`localizationService.GetString(() => MyResource.SomeLabel);` and it throws a `KeyNotFoundException`. It seems like using the `AddString()` method does not work for strongly typed resources? 

We have tried using standard key format like "/MyResource/SomeLabel" as well when adding resources with same result. 

We are pretty sure it is the same localizationService instance we're using in the test. I can create repro example as well.

We're using DbLocalizationProvider.EPiServer, Version=5.8.2.0.

**Comment by valdisiljuconoks** [comment]
v7.0 is coming closer to the end of the pre-release. In CMS12 now this is possible:

```csharp
[Fact]
public void TestWithEpiserverMemoryProvider()
{
    var localizationService = new MemoryLocalizationService();
    localizationService.AddString(CultureInfo.CurrentUICulture, "DbLocalizationProvider.EPiServer.Tests.MyResource.SomeLabel", "Some label");
    localizationService.AddString(CultureInfo.CurrentUICulture, "DbLocalizationProvider.EPiServer.Tests.MyResource.SomeLabelWithPlaceholder", "Some label `{Name}`");

    var result = localizationService.GetString(() => MyResource.SomeLabel);
    Assert.Equal("Some label", result);

    var result2 = localizationService.GetString(() => MyResource.SomeLabelWithPlaceholder, new { Name = "John" });
    Assert.Equal("Some label `John`", result2);
}
```
